import type { DamageType, WeaponProperty } from "#/types.ts";

/* eslint-disable no-magic-numbers -- SRD equipment tables are literal rules data */

export const CHARACTER_WEAPONS = [
  "club",
  "dagger",
  "greatclub",
  "handaxe",
  "javelin",
  "lightHammer",
  "mace",
  "quarterstaff",
  "sickle",
  "spear",
  "dart",
  "lightCrossbow",
  "shortbow",
  "sling",
  "battleaxe",
  "flail",
  "glaive",
  "greataxe",
  "greatsword",
  "halberd",
  "lance",
  "longsword",
  "maul",
  "morningstar",
  "pike",
  "rapier",
  "scimitar",
  "shortsword",
  "trident",
  "warhammer",
  "warPick",
  "whip",
  "blowgun",
  "handCrossbow",
  "heavyCrossbow",
  "longbow",
  "musket",
  "pistol",
] as const;
export type CharacterWeapon = (typeof CHARACTER_WEAPONS)[number];

export interface CharacterWeaponData {
  readonly displayName: string;
  readonly costGp: number;
  readonly damageType: DamageType;
  readonly isMelee: boolean;
  readonly damageDie?: number;
  readonly diceCount?: number;
  readonly versatileDie?: number;
  readonly properties: ReadonlyArray<WeaponProperty>;
}

export const WEAPON_DATA: Readonly<
  Record<CharacterWeapon, CharacterWeaponData>
> = {
  club: {
    displayName: "Club",
    costGp: 0.1,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 4,
    properties: ["light"],
  },
  dagger: {
    displayName: "Dagger",
    costGp: 2,
    damageType: "piercing",
    isMelee: true,
    damageDie: 4,
    properties: ["finesse", "light", "thrown"],
  },
  greatclub: {
    displayName: "Greatclub",
    costGp: 0.2,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 8,
    properties: ["twoHanded"],
  },
  handaxe: {
    displayName: "Handaxe",
    costGp: 5,
    damageType: "slashing",
    isMelee: true,
    damageDie: 6,
    properties: ["light", "thrown"],
  },
  javelin: {
    displayName: "Javelin",
    costGp: 0.5,
    damageType: "piercing",
    isMelee: true,
    damageDie: 6,
    properties: ["thrown"],
  },
  lightHammer: {
    displayName: "Light Hammer",
    costGp: 2,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 4,
    properties: ["light", "thrown"],
  },
  mace: {
    displayName: "Mace",
    costGp: 5,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 6,
    properties: [],
  },
  quarterstaff: {
    displayName: "Quarterstaff",
    costGp: 0.2,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 6,
    versatileDie: 8,
    properties: ["versatile"],
  },
  sickle: {
    displayName: "Sickle",
    costGp: 1,
    damageType: "slashing",
    isMelee: true,
    damageDie: 4,
    properties: ["light"],
  },
  spear: {
    displayName: "Spear",
    costGp: 1,
    damageType: "piercing",
    isMelee: true,
    damageDie: 6,
    versatileDie: 8,
    properties: ["thrown", "versatile"],
  },
  dart: {
    displayName: "Dart",
    costGp: 0.05,
    damageType: "piercing",
    isMelee: false,
    damageDie: 4,
    properties: ["finesse", "thrown"],
  },
  lightCrossbow: {
    displayName: "Light Crossbow",
    costGp: 25,
    damageType: "piercing",
    isMelee: false,
    damageDie: 8,
    properties: ["ammunition", "loading", "twoHanded"],
  },
  shortbow: {
    displayName: "Shortbow",
    costGp: 25,
    damageType: "piercing",
    isMelee: false,
    damageDie: 6,
    properties: ["ammunition", "twoHanded"],
  },
  sling: {
    displayName: "Sling",
    costGp: 0.1,
    damageType: "bludgeoning",
    isMelee: false,
    damageDie: 4,
    properties: ["ammunition"],
  },
  battleaxe: {
    displayName: "Battleaxe",
    costGp: 10,
    damageType: "slashing",
    isMelee: true,
    damageDie: 8,
    versatileDie: 10,
    properties: ["versatile"],
  },
  flail: {
    displayName: "Flail",
    costGp: 10,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 8,
    properties: [],
  },
  glaive: {
    displayName: "Glaive",
    costGp: 20,
    damageType: "slashing",
    isMelee: true,
    damageDie: 10,
    properties: ["heavy", "reach", "twoHanded"],
  },
  greataxe: {
    displayName: "Greataxe",
    costGp: 30,
    damageType: "slashing",
    isMelee: true,
    damageDie: 12,
    properties: ["heavy", "twoHanded"],
  },
  greatsword: {
    displayName: "Greatsword",
    costGp: 50,
    damageType: "slashing",
    isMelee: true,
    damageDie: 6,
    diceCount: 2,
    properties: ["heavy", "twoHanded"],
  },
  halberd: {
    displayName: "Halberd",
    costGp: 20,
    damageType: "slashing",
    isMelee: true,
    damageDie: 10,
    properties: ["heavy", "reach", "twoHanded"],
  },
  lance: {
    displayName: "Lance",
    costGp: 10,
    damageType: "piercing",
    isMelee: true,
    damageDie: 10,
    properties: ["heavy", "reach", "twoHanded"],
  },
  longsword: {
    displayName: "Longsword",
    costGp: 15,
    damageType: "slashing",
    isMelee: true,
    damageDie: 8,
    versatileDie: 10,
    properties: ["versatile"],
  },
  maul: {
    displayName: "Maul",
    costGp: 10,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 6,
    diceCount: 2,
    properties: ["heavy", "twoHanded"],
  },
  morningstar: {
    displayName: "Morningstar",
    costGp: 15,
    damageType: "piercing",
    isMelee: true,
    damageDie: 8,
    properties: [],
  },
  pike: {
    displayName: "Pike",
    costGp: 5,
    damageType: "piercing",
    isMelee: true,
    damageDie: 10,
    properties: ["heavy", "reach", "twoHanded"],
  },
  rapier: {
    displayName: "Rapier",
    costGp: 25,
    damageType: "piercing",
    isMelee: true,
    damageDie: 8,
    properties: ["finesse"],
  },
  scimitar: {
    displayName: "Scimitar",
    costGp: 25,
    damageType: "slashing",
    isMelee: true,
    damageDie: 6,
    properties: ["finesse", "light"],
  },
  shortsword: {
    displayName: "Shortsword",
    costGp: 10,
    damageType: "piercing",
    isMelee: true,
    damageDie: 6,
    properties: ["finesse", "light"],
  },
  trident: {
    displayName: "Trident",
    costGp: 5,
    damageType: "piercing",
    isMelee: true,
    damageDie: 8,
    versatileDie: 10,
    properties: ["thrown", "versatile"],
  },
  warhammer: {
    displayName: "Warhammer",
    costGp: 15,
    damageType: "bludgeoning",
    isMelee: true,
    damageDie: 8,
    versatileDie: 10,
    properties: ["versatile"],
  },
  warPick: {
    displayName: "War Pick",
    costGp: 5,
    damageType: "piercing",
    isMelee: true,
    damageDie: 8,
    versatileDie: 10,
    properties: ["versatile"],
  },
  whip: {
    displayName: "Whip",
    costGp: 2,
    damageType: "slashing",
    isMelee: true,
    damageDie: 4,
    properties: ["finesse", "reach"],
  },
  blowgun: {
    displayName: "Blowgun",
    costGp: 10,
    damageType: "piercing",
    isMelee: false,
    damageDie: 1,
    properties: ["ammunition", "loading"],
  },
  handCrossbow: {
    displayName: "Hand Crossbow",
    costGp: 75,
    damageType: "piercing",
    isMelee: false,
    damageDie: 6,
    properties: ["ammunition", "light", "loading"],
  },
  heavyCrossbow: {
    displayName: "Heavy Crossbow",
    costGp: 50,
    damageType: "piercing",
    isMelee: false,
    damageDie: 10,
    properties: ["ammunition", "heavy", "loading", "twoHanded"],
  },
  longbow: {
    displayName: "Longbow",
    costGp: 50,
    damageType: "piercing",
    isMelee: false,
    damageDie: 8,
    properties: ["ammunition", "heavy", "twoHanded"],
  },
  musket: {
    displayName: "Musket",
    costGp: 500,
    damageType: "piercing",
    isMelee: false,
    damageDie: 12,
    properties: ["ammunition", "loading", "twoHanded"],
  },
  pistol: {
    displayName: "Pistol",
    costGp: 250,
    damageType: "piercing",
    isMelee: false,
    damageDie: 10,
    properties: ["ammunition", "loading"],
  },
};
