import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass } from "#/types.ts";

const E_TO_G_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-E-G.md";

export const GLADIATOR = {
  provenance: srdRulesProvenance(E_TO_G_SOURCE_DOCUMENT, "Gladiator"),
  name: "Gladiator",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(16),
  initiativeMod: abilityModifier(5),
  maxHp: 112,
  hitDice: 15,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 18,
    dex: 15,
    con: 16,
    int: 10,
    wis: 12,
    cha: 15,
  },
  saveProficiencies: new Set(["str", "dex", "con"]),
  skillBonuses: monsterSkillBonuses({
    athletics: 10,
    performance: 5,
  }),
  cr: { type: "CRN", value: 5 },
  proficiencyBonus: 3,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 11,
  languages: ["Common"],
  gear: ["Shield", "Spears (3)", "Studded Leather Armor"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The gladiator makes three Spear attacks. It can replace one attack with a use of Shield Bash.",
      slots: [
        { type: "MSpecialAbility", name: "Spear" },
        { type: "MSpecialAbility", name: "Spear" },
        { type: "MSpecialAbility", name: "Shield Bash" },
      ],
    },
    {
      kind: "text",
      id: "spear",
      name: "Spear",
      text: "*Melee or Ranged Attack Roll:* +7, reach 5 ft. or range 20/60 ft. *Hit:* 11 (2d6 + 4) Piercing damage.",
      blockerFamily: "attackProjectionGap",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
    {
      kind: "saveEffectAction",
      id: "shieldBash",
      name: "Shield Bash",
      text: "*Strength Saving Throw:* DC 15, one creature within 5 feet that the gladiator can see. *Failure:* 9 (2d4 + 4) Bludgeoning damage. If the target is a Medium or smaller creature, it has the Prone condition.",
      save: {
        ability: "str",
        dc: 15,
        rangeFeet: 5,
        target: "oneCreatureYouCanSee",
        damageOnFail: 9,
        damageType: "bludgeoning",
        conditionOnFail: {
          condition: "prone",
          targetSizeAtMost: "medium",
        },
      },
    },
  ],
  bonusActions: [],
  reactions: [
    {
      kind: "text",
      id: "parry",
      name: "Parry",
      text: "*Trigger:* The gladiator is hit by a melee attack roll while holding a weapon. *Response:* The gladiator adds 3 to its AC against that attack, possibly causing it to miss.",
      blockerFamily: "reactiveDefense",
      nonExecutableReason:
        "Reactive AC boosts are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const GUARD = {
  provenance: srdRulesProvenance(E_TO_G_SOURCE_DOCUMENT, "Guards > Guard"),
  name: "Guard",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(16),
  initiativeMod: abilityModifier(1),
  maxHp: 11,
  hitDice: 2,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 13,
    dex: 12,
    con: 12,
    int: 10,
    wis: 11,
    cha: 10,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    perception: 2,
  }),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 12,
  languages: ["Common"],
  gear: ["Chain Shirt", "Shield", "Spear"],
  traits: [],
  actions: [
    {
      kind: "attack",
      id: "spear",
      name: "Spear",
      text: "*Melee or Ranged Attack Roll:* +3, reach 5 ft. or range 20/60 ft. *Hit:* 4 (1d6 + 1) Piercing damage.",
      attack: {
        name: "Spear",
        attackBonus: 3,
        reach: 5,
        rangeNormal: 20,
        rangeLong: 60,
        damageAmount: 4,
        damageType: "piercing",
        isRanged: false,
        attackMode: "meleeOrRanged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const GUARD_CAPTAIN = {
  provenance: srdRulesProvenance(
    E_TO_G_SOURCE_DOCUMENT,
    "Guards > Guard Captain",
  ),
  name: "Guard Captain",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(18),
  initiativeMod: abilityModifier(4),
  maxHp: 75,
  hitDice: 10,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 18,
    dex: 14,
    con: 16,
    int: 12,
    wis: 14,
    cha: 13,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    athletics: 6,
    perception: 4,
  }),
  cr: { type: "CRN", value: 4 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 14,
  languages: ["Common"],
  gear: ["Breastplate", "Javelins (6)", "Longsword", "Shield"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The guard makes two attacks, using Javelin or Longsword in any combination.",
      slots: [
        { type: "MSpecialAbility", name: "Javelin" },
        { type: "MSpecialAbility", name: "Longsword" },
      ],
    },
    {
      kind: "text",
      id: "javelin",
      name: "Javelin",
      text: "*Melee or Ranged Attack Roll:* +6, reach 5 ft. or range 30/120 ft. *Hit:* 14 (3d6 + 4) Piercing damage.",
      blockerFamily: "attackProjectionGap",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
    {
      kind: "text",
      id: "longsword",
      name: "Longsword",
      text: "*Melee Attack Roll:* +6, reach 5 ft. *Hit:* 15 (2d10 + 4) Slashing damage.",
      blockerFamily: "attackProjectionGap",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
