export {
  classSpellcastingCreationAtLevel,
  isListPreparedSpellcastingCreation,
  isPactMagicSpellcastingCreation,
  isWizardSpellcastingCreation,
} from "./class-spellcasting.ts";

export {
  ALIGNMENT_MORALITIES,
  ALIGNMENT_ORDERS,
  CHARACTER_CLASS_LEVELS,
  ABILITY_SCORE_GENERATION_DRAFT_PATH,
  CHARACTER_DRAFT_CHOICE_PATHS,
  CHARACTER_DRAFT_PATHS,
  CREATION_BATCH_ISSUE_CODES,
  CREATION_FILL_ISSUE_CODES,
  CREATION_FINALIZATION_ISSUE_CODES,
  CHARACTER_EQUIPMENT_ITEM_SLOTS,
  LOADOUT_SLOTS,
  STANDARD_LANGUAGES,
  SUPPORTED_ABILITY_SCORE_METHODS,
  UNIT_CHOICE_KEYS,
  abilityScoreAssignment,
  characterDraftId,
  characterDraconicAncestrySelection,
  characterClassLevel,
  characterEquipmentItemId,
  characterEquipmentItemSourceFromId,
  characterEquipmentItemUnitId,
  characterEquipmentItemUnitIdFromLoadoutEquipmentUnitId,
  boundedChoiceCardinality,
  choiceCardinalityBounds,
  choiceCardinalityMax,
  creationChoiceOptionId,
  creationHoleId,
  creationSessionId,
  draftRevision,
  eldritchInvocationId,
  exactChoiceCardinality,
  hitDieSize,
  hitDieTotal,
  loadoutEquipmentUnitId,
  loadoutSourceHoleIdText,
  loadoutSourceKey,
  parseCharacterEquipmentItemId,
  parseCreationHoleId,
  parseLoadoutSourceKey,
  parseUnitChoiceSourceKey,
  sorcererMetamagicOptionId,
  unitChoiceKey,
  unitChoiceSourceHoleIdText,
  unitChoiceSourceKey,
  unitChoiceSourceUnitId,
  type AbilityScoreAssignment,
  type AbilityScoreGenerationSource,
  type AbilityScoreGenerationSelection,
  type AlignmentMorality,
  type AlignmentOrder,
  type BackgroundAbilityScoreIncreaseSelection,
  type CharacterAlignment,
  type CharacterBuild,
  type CharacterBuildAbilityScores,
  type CharacterBuildBookOfShadowsSpellAccess,
  type CharacterBuildClassFeatureLanguage,
  type CharacterBuildDraconicAncestryFact,
  type CharacterBuildEquipment,
  type CharacterBuildEldritchInvocationRepeatableChoice,
  type CharacterBuildEldritchInvocationSelection,
  type CharacterBuildFeature,
  type CharacterBuildGnomishLineageFact,
  type CharacterBuildGnomishLineageId,
  type CharacterBuildGnomishLineageSpellcastingAbility,
  type CharacterBuildHitDiePool,
  type CharacterBuildHitPoints,
  type CharacterBuildLoadout,
  type CharacterBuildOwnedEquipmentItem,
  type CharacterBuildPactMagicSlotPool,
  type CharacterBuildProficiencies,
  type CharacterBuildProficiencyChoiceSubject,
  type CharacterBuildResource,
  type CharacterBuildSpeciesChoiceFacts,
  type CharacterBuildSpellcasting,
  type CharacterBuildSpellcastingFocus,
  type CharacterBuildSpellcastingSlotPool,
  type CharacterBuildSpellcastingSource,
  type CharacterBuildSpellLevel,
  type CharacterBuildSpellSlotCapacity,
  type CharacterBuildSpellSlotCount,
  type CharacterBuildSpellSlotPools,
  type CharacterChoiceSelection,
  type CharacterClassLevel,
  type CharacterCreationAbilityScoreAssignment,
  type CharacterDraft,
  type CharacterDraftChoicePath,
  type CharacterDraftId,
  type CharacterDraftPath,
  type CharacterDraconicAncestrySelection,
  type CharacterDraftSelections,
  type CharacterEquipmentItemId,
  type CharacterEquipmentItemIdIssue,
  type CharacterEquipmentItemIdText,
  type CharacterEquipmentItemSlot,
  type CharacterEquipmentItemSource,
  type CharacterEquipmentItemUnitId,
  type CharacterEquipmentItemUnitIdIssue,
  type CharacterEquipmentSelection,
  type CharacterSelectedChoiceOption,
  type CharacterStartingLanguages,
  type ChoiceCardinality,
  type ChoiceCreationHoleSource,
  type ChoiceCount,
  type ChoiceMinimumCount,
  type CreationBatchFillInput,
  type CreationBatchFillIssue,
  type CreationBatchFillResult,
  type CreationBatchIssue,
  type CreationBatchIssueCode,
  type CreationChoiceOption,
  type CreationChoiceOptionId,
  type CreationFill,
  type CreationFillIssue,
  type CreationFillIssueCode,
  type CreationFinalizationIssue,
  type CreationFinalizationIssueCode,
  type CreationFinalizationResult,
  type CreationHole,
  type CreationHoleId,
  type CreationHoleIdText,
  type CreationHoleSource,
  type CreationSession,
  type CreationSessionId,
  type DraftRevision,
  type EldritchInvocationId,
  type DraftChoiceCreationHoleSource,
  type DraftCreationHoleSource,
  type FillIndex,
  type HitDieSize,
  type HitDieTotal,
  type LoadoutEquipmentUnitId,
  type LoadoutEquipmentUnitIdIssue,
  type LoadoutSlot,
  type LoadoutSource,
  type LoadoutSourceKey,
  type LoadoutSourceKeyIssue,
  type LoadoutSourceKeyText,
  type NonEmptyReadonlyArray,
  type SelectableStandardLanguage,
  type SorcererMetamagicOptionId,
  type SorcererMetamagicOptionIdIssue,
  type StandardLanguage,
  type SupportedAbilityScoreMethod,
  type TwoAndOneBackgroundAbilityScoreIncreaseSelection,
  type UnitChoiceKey,
  type UnitChoiceSourceKey,
  type UnitChoiceSourceKeyIssue,
  type UnitChoiceSourceKeyText,
  type UnitChoiceSource,
  type UnitChoiceSourceUnitId,
  type UnitChoiceSourceUnitIdIssue,
  type UnitCatalog,
  type UnitRef,
  type UnitRefSelectedOption,
} from "./types.ts";
export {
  languageFromSurfaceLanguageId,
  type SurfaceLanguageIdIssue,
} from "./language-codecs.ts";

// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.class-feature-feat-choice
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.weapon-mastery-choice
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.eldritch-invocation-choice
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.class-feature-option-projection
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.skill-expertise-choice
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.warlock-pact-magic-advancement
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.class-feature-resource-projection
// UNIT-PROFILE-COVERAGE: runtime-owner character-creation.class-feature-source-fact-projection

export {
  LEVEL_ONE_ELDRITCH_INVOCATION_OPTIONS,
  SRD_ELDRITCH_INVOCATION_OPTIONS,
  eldritchInvocationOptionForInvocationId,
  eldritchInvocationRepeatableChoiceSatisfiesRule,
  knownWarlockCantripSatisfiesEldritchInvocationRule,
  levelOneEldritchInvocationChoiceOptions,
  type EldritchInvocationOption,
  type EldritchInvocationPrerequisite,
} from "./eldritch-invocations.ts";
export {
  createCharacterDraft,
  parseCharacterDraft,
  type CharacterDraftParseIssue,
} from "./draft.ts";
export { discoverCreationHoles } from "./discovery.ts";
export { fillCreationHoles } from "./fill-reducer.ts";
export {
  finalizeCharacterDraft,
  characterBuildArmorTraining,
  characterBuildFeatureUnitIds,
  characterBuildHitPoints,
  characterBuildProficiencies,
  characterBuildResources,
  characterBuildSpellcastingSlotCapacity,
  characterBuildUnitRefs,
} from "./finalization.ts";
export {
  characterBuildGnomishLineageTraitProjection,
  type CharacterBuildGnomishLineageOption,
  type CharacterBuildGnomishLineageTraitProjection,
  type CharacterBuildGnomishLineageTraitProjectionIssue,
} from "./gnomish-lineage.ts";
export {
  isWeaponMasteryChoiceFeature,
  weaponMasteryChoiceProfileForFeature,
  type WeaponMasteryChoiceFeature,
  type WeaponMasteryChoiceProfile,
} from "./weapon-mastery.ts";
export {
  DRUID_WILD_SHAPE_UNIT_ID,
  characterBuildDruidWildShapeFacts,
  replaceDruidWildShapeKnownForm,
  validateDruidWildShapeKnownForms,
  validateDruidWildShapeKnownFormRecords,
  type CharacterBuildDruidWildShapeFacts,
  type CharacterBuildDruidWildShapeFactsIssue,
  type CharacterBuildDruidWildShapeKnownFormReplacement,
} from "./druid-wild-shape.ts";
export {
  MONK_MONKS_FOCUS_UNIT_ID,
  characterBuildMonksFocusFacts,
  type CharacterBuildMonksFocusFacts,
  type CharacterBuildMonksFocusFactsIssue,
} from "./monk-focus.ts";
export {
  MONK_MARTIAL_ARTS_UNIT_ID,
  MONK_UNCANNY_METABOLISM_UNIT_ID,
  characterBuildMonkUncannyMetabolismFacts,
  type CharacterBuildMonkUncannyMetabolismFacts,
  type CharacterBuildMonkUncannyMetabolismFactsIssue,
} from "./monk-uncanny-metabolism.ts";
export {
  SORCERER_FONT_OF_MAGIC_UNIT_ID,
  characterBuildSorcererFontOfMagicFacts,
  fontOfMagicSpellSlotCreationOption,
  type CharacterBuildSorcererFontOfMagicFacts,
  type CharacterBuildSorcererFontOfMagicFactsIssue,
} from "./sorcerer-font-of-magic.ts";
export {
  SORCERER_METAMAGIC_UNIT_ID,
  characterBuildSorcererMetamagicFacts,
  parseSorcererMetamagicOptionId,
  type CharacterBuildSorcererMetamagicFacts,
  type CharacterBuildSorcererMetamagicFactsIssue,
  type CharacterBuildSorcererMetamagicOptionFact,
} from "./sorcerer-metamagic.ts";
export {
  classLevelLinearValueAtClassLevel,
  classLevelChoiceCountAtLevel,
  isClassLevelLinearPerLevel,
  isClassLevelThresholdTiers,
  thresholdTierValueAtClassLevel,
  type ClassLevelLinearPerLevel,
  type ClassLevelThresholdTiers,
} from "./class-level-scaling.ts";
export {
  classNameFromClassUnit,
  classUnitIdFromClassUnit,
  classUnitIdFromUnitId,
  classUnitIdToClassName,
  type CharacterProgression,
  type CharacterProgressionIssue,
  type ClassUnitNameIssue,
} from "./character-progression-algebra.ts";
export {
  classLevelForUnit,
  classUnitId,
  computeTotalLevel,
  characterProgressionWithClassLevelGain,
  characterTotalLevelHitPointRule,
  hitPointRuleLabel,
  hitPointRuleOptionSuffix,
  hitPointsAfterLevelOneMultiplier,
  progressionClassLevels,
  progressionClassUnitIds,
  startingClassUnitId,
  type CharacterProgressionClassLevel,
  type CharacterProgressionEntry,
  type CharacterTotalLevelHitPointRule,
  type CharacterProgressionLevelIssue,
  type ClassUnitId,
  type FixedHigherLevelClassHitPointRule,
  type ClassHitPointRule,
  type LevelOneClassHitPointRule,
} from "./character-progression-types.ts";
export {
  advanceCharacterBuildClassLevel,
  classLevelGainWithFightingStyleCantripReplacement,
  fighterClassUnitId,
  fighterLevelGainWithFightingStyleReplacement,
  fightingStyleCantripUnitId,
  fightingStyleFeatUnitId,
  sorcererClassUnitId,
  sorcererLevelGain,
  weaponMasteryFeatureUnitId,
  weaponMasteryLevelGain,
  weaponMasteryWeaponUnitId,
  warlockClassUnitId,
  warlockLevelGain,
  type CharacterBuildAdvancementIssue,
  type CharacterBuildClassLevelGain,
  type CharacterBuildFighterFightingStyleReplacementLevelGain,
  type CharacterBuildFightingStyleCantripReplacementLevelGain,
  type CharacterBuildListPreparedSpellcastingLevelGain,
  type CharacterBuildPlainClassLevelGain,
  type CharacterBuildSorcererMetamagicLevelGain,
  type CharacterBuildWeaponMasteryLevelGain,
  type CharacterBuildWarlockEldritchInvocationSelectionInput,
  type CharacterBuildWarlockLevelGain,
  type CharacterBuildWarlockPactMagicLevelGain,
  type FighterClassUnitId,
  type FightingStyleCantripUnitId,
  type FightingStyleFeatUnitId,
  type SorcererClassUnitId,
  type WeaponMasteryFeatureUnitId,
  type WeaponMasteryWeaponUnitId,
  type WarlockClassUnitId,
} from "./character-build-advancement.ts";
export {
  BACKGROUND_ABILITY_SCORE_INCREASE_CHOICE_KEY,
  BACKGROUND_EQUIPMENT_CHOICE_KEY,
  BACKGROUND_TOOL_CHOICE_KEY,
  CLASS_EQUIPMENT_CHOICE_KEY,
  ELDRITCH_INVOCATIONS_CHOICE_KEY,
  GNOMISH_LINEAGE_CHOICE_KEY,
  GNOMISH_LINEAGE_SPELLCASTING_ABILITY_CHOICE_KEY,
  CLASS_FEATURE_FEAT_CHOICE_KEY,
  CLASS_SKILL_PROFICIENCY_CHOICE_KEY,
  EQUIPMENT_PURCHASE_CHOICE_KEY,
  LOADOUT_ARMOR_SLOT,
  LOADOUT_SHIELD_SLOT,
  LOADOUT_WEAPON_SLOT,
  PHASE1_ALIGNMENT_OPTION_ID,
  PHASE1_ARMOR_CHAIN_MAIL_UNIT_ID,
  PHASE1_BACKGROUND_ABILITY_SCORE_INCREASE_OPTION_ID,
  PHASE1_BACKGROUND_EQUIPMENT_OPTION_ID,
  PHASE1_BACKGROUND_SOLDIER_UNIT_ID,
  PHASE1_BACKGROUND_TOOL_OPTION_ID,
  PHASE1_CLASS_EQUIPMENT_OPTION_ID,
  PHASE1_CLASS_FIGHTER_UNIT_ID,
  PHASE1_FIGHTING_STYLE_ARCHERY_UNIT_ID,
  PHASE1_FIGHTING_STYLE_DEFENSE_UNIT_ID,
  PHASE1_FIGHTING_STYLE_GREAT_WEAPON_FIGHTING_UNIT_ID,
  PHASE1_FIGHTING_STYLE_TWO_WEAPON_FIGHTING_UNIT_ID,
  PHASE1_LOADOUT_ARMOR_OPTION_ID,
  PHASE1_LOADOUT_SHIELD_OPTION_ID,
  PHASE1_LOADOUT_WEAPON_OPTION_ID,
  PHASE1_SHIELD_UNIT_ID,
  SRD_GNOME_SPECIES_UNIT_ID,
  PHASE1_SPECIES_ORC_UNIT_ID,
  PHASE1_WEAPON_LONGSWORD_UNIT_ID,
  PHASE1_WEAPON_MASTERY_UNIT_IDS,
  HUNTERS_PREY_CHOICE_KEY,
  SORCERER_METAMAGIC_OPTIONS_CHOICE_KEY,
  SUPPORTED_FIGHTER_SKILL_OPTION_IDS,
  SUPPORTED_LANGUAGE_OPTION_IDS,
  WEAPON_MASTERY_OPTIONS_CHOICE_KEY,
  progressionOptionId,
} from "./phase1-manifest.ts";
