import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass } from "#/types.ts";

const T_TO_Z_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-T-Z.md";

export const TOUGH = {
  provenance: srdRulesProvenance(T_TO_Z_SOURCE_DOCUMENT, "Toughs > Tough"),
  name: "Tough",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(12),
  initiativeMod: abilityModifier(1),
  maxHp: 32,
  hitDice: 5,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 15,
    dex: 12,
    con: 14,
    int: 10,
    wis: 10,
    cha: 11,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CR_Half" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common"],
  gear: ["Heavy Crossbow", "Leather Armor", "Mace"],
  traits: [
    {
      kind: "text",
      id: "packTactics",
      name: "Pack Tactics",
      text: "The tough has Advantage on an attack roll against a creature if at least one of the tough's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      blockerFamily: "combatModifierTrait",
      nonExecutableReason:
        "Conditional ally-based attack advantage from monster traits is not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "attack",
      id: "mace",
      name: "Mace",
      text: "*Melee Attack Roll:* +4, reach 5 ft. *Hit:* 5 (1d6 + 2) Bludgeoning damage.",
      attack: {
        name: "Mace",
        attackBonus: 4,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 5,
        damageType: "bludgeoning",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "attack",
      id: "heavyCrossbow",
      name: "Heavy Crossbow",
      text: "*Ranged Attack Roll:* +3, range 100/400 ft. *Hit:* 6 (1d10 + 1) Piercing damage.",
      attack: {
        name: "Heavy Crossbow",
        attackBonus: 3,
        reach: 0,
        rangeNormal: 100,
        rangeLong: 400,
        damageAmount: 6,
        damageType: "piercing",
        isRanged: true,
        attackMode: "ranged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const TOUGH_BOSS = {
  provenance: srdRulesProvenance(T_TO_Z_SOURCE_DOCUMENT, "Toughs > Tough Boss"),
  name: "Tough Boss",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(16),
  initiativeMod: abilityModifier(2),
  maxHp: 82,
  hitDice: 11,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 17,
    dex: 14,
    con: 16,
    int: 11,
    wis: 10,
    cha: 11,
  },
  saveProficiencies: new Set(["str", "con", "cha"]),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CRN", value: 4 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common plus one other language"],
  gear: ["Chain Mail", "Heavy Crossbow", "Warhammer"],
  traits: [
    {
      kind: "text",
      id: "packTactics",
      name: "Pack Tactics",
      text: "The tough has Advantage on an attack roll against a creature if at least one of the tough's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      blockerFamily: "combatModifierTrait",
      nonExecutableReason:
        "Conditional ally-based attack advantage from monster traits is not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The tough makes two attacks, using Warhammer or Heavy Crossbow in any combination.",
      slots: [
        { type: "MSpecialAbility", name: "Warhammer" },
        { type: "MSpecialAbility", name: "Heavy Crossbow" },
      ],
    },
    {
      kind: "text",
      id: "warhammer",
      name: "Warhammer",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 12 (2d8 + 3) Bludgeoning damage. If the target is a Large or smaller creature, the tough pushes the target up to 10 feet straight away from itself.",
      blockerFamily: "attackRider",
      nonExecutableReason:
        "On-hit forced movement from monster weapon attacks is not yet projected into the generic monster attack surface.",
    },
    {
      kind: "text",
      id: "heavyCrossbow",
      name: "Heavy Crossbow",
      text: "*Ranged Attack Roll:* +4, range 100/400 ft. *Hit:* 13 (2d10 + 2) Piercing damage.",
      blockerFamily: "attackProjectionGap",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const WARRIOR_INFANTRY = {
  provenance: srdRulesProvenance(
    T_TO_Z_SOURCE_DOCUMENT,
    "Warriors > Warrior Infantry",
  ),
  name: "Warrior Infantry",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(13),
  initiativeMod: abilityModifier(0),
  maxHp: 9,
  hitDice: 2,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 13,
    dex: 11,
    con: 11,
    int: 8,
    wis: 11,
    cha: 8,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common"],
  gear: ["Chain Shirt", "Spear"],
  traits: [
    {
      kind: "text",
      id: "packTactics",
      name: "Pack Tactics",
      text: "The warrior has Advantage on an attack roll against a creature if at least one of the warrior's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      blockerFamily: "combatModifierTrait",
      nonExecutableReason:
        "Conditional ally-based attack advantage from monster traits is not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "attack",
      id: "spear",
      name: "Spear",
      text: "*Melee or Ranged Attack Roll:* +3, reach 5 ft. or range 20/60 ft. *Hit:* 4 (1d6 + 1) Piercing damage.",
      attack: {
        name: "Spear",
        attackBonus: 3,
        reach: 5,
        rangeNormal: 20,
        rangeLong: 60,
        damageAmount: 4,
        damageType: "piercing",
        isRanged: false,
        attackMode: "meleeOrRanged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const WARRIOR_VETERAN = {
  provenance: srdRulesProvenance(
    T_TO_Z_SOURCE_DOCUMENT,
    "Warriors > Warrior Veteran",
  ),
  name: "Warrior Veteran",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(17),
  initiativeMod: abilityModifier(3),
  maxHp: 65,
  hitDice: 10,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 16,
    dex: 13,
    con: 14,
    int: 10,
    wis: 11,
    cha: 10,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    athletics: 5,
    perception: 2,
  }),
  cr: { type: "CRN", value: 3 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 12,
  languages: ["Common plus one other language"],
  gear: ["Greatsword", "Heavy Crossbow", "Splint Armor"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The warrior makes two Greatsword or Heavy Crossbow attacks.",
      slots: [
        { type: "MAttack", name: "Greatsword" },
        { type: "MSpecialAbility", name: "Heavy Crossbow" },
      ],
    },
    {
      kind: "attack",
      id: "greatsword",
      name: "Greatsword",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 10 (2d6 + 3) Slashing damage.",
      attack: {
        name: "Greatsword",
        attackBonus: 5,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 10,
        damageType: "slashing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "text",
      id: "heavyCrossbow",
      name: "Heavy Crossbow",
      text: "*Ranged Attack Roll:* +3, range 100/400 ft. *Hit:* 12 (2d10 + 1) Piercing damage.",
      blockerFamily: "attackProjectionGap",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
  ],
  bonusActions: [],
  reactions: [
    {
      kind: "text",
      id: "parry",
      name: "Parry",
      text: "*Trigger:* The warrior is hit by a melee attack roll while holding a weapon. *Response:* The warrior adds 2 to its AC against that attack, possibly causing it to miss.",
      blockerFamily: "reactiveDefense",
      nonExecutableReason:
        "Reactive AC boosts are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
