import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass } from "#/types.ts";

const H_TO_L_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-H-L.md";
const M_TO_O_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-M-O.md";
const P_TO_S_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-P-S.md";

export const KNIGHT = {
  provenance: {
    edition: "SRD 5.2.1",
    document: H_TO_L_SOURCE_DOCUMENT,
    section: "Knight",
  },
  name: "Knight",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(18),
  initiativeMod: abilityModifier(0),
  maxHp: 52,
  hitDice: 8,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 16,
    dex: 11,
    con: 14,
    int: 11,
    wis: 11,
    cha: 15,
  },
  saveProficiencies: new Set(["con", "wis"]),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CRN", value: 3 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(["frightened"]),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common plus one other language"],
  gear: ["Greatsword", "Heavy Crossbow", "Plate Armor"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The knight makes two attacks, using Greatsword or Heavy Crossbow in any combination.",
      slots: [
        { type: "MSpecialAbility", name: "Greatsword" },
        { type: "MSpecialAbility", name: "Heavy Crossbow" },
      ],
    },
    {
      kind: "text",
      id: "greatsword",
      name: "Greatsword",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 10 (2d6 + 3) Slashing damage plus 4 (1d8) Radiant damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
    {
      kind: "text",
      id: "heavyCrossbow",
      name: "Heavy Crossbow",
      text: "*Ranged Attack Roll:* +2, range 100/400 ft. *Hit:* 11 (2d10) Piercing damage plus 4 (1d8) Radiant damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
  ],
  bonusActions: [],
  reactions: [
    {
      kind: "text",
      id: "parry",
      name: "Parry",
      text: "*Trigger:* The knight is hit by a melee attack roll while holding a weapon. *Response:* The knight adds 2 to its AC against that attack, possibly causing it to miss.",
      nonExecutableReason:
        "Reactive AC boosts are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const KOBOLD_WARRIOR = {
  provenance: {
    edition: "SRD 5.2.1",
    document: H_TO_L_SOURCE_DOCUMENT,
    section: "Kobold > Kobold Warrior",
  },
  name: "Kobold Warrior",
  creatureType: "dragon",
  creatureSize: "small",
  ac: armorClass(14),
  initiativeMod: abilityModifier(2),
  maxHp: 7,
  hitDice: 3,
  hitDieType: 6,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 7,
    dex: 15,
    con: 9,
    int: 8,
    wis: 7,
    cha: 8,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({ darkvision: 60 }),
  passivePerception: 8,
  languages: ["Common", "Draconic"],
  gear: ["Daggers (3)"],
  traits: [
    {
      kind: "text",
      id: "packTactics",
      name: "Pack Tactics",
      text: "The kobold has Advantage on an attack roll against a creature if at least one of the kobold's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      nonExecutableReason:
        "Conditional ally-based attack advantage from monster traits is not yet projected into the generic monster runtime surface.",
    },
    {
      kind: "text",
      id: "sunlightSensitivity",
      name: "Sunlight Sensitivity",
      text: "While in sunlight, the kobold has Disadvantage on ability checks and attack rolls.",
      nonExecutableReason:
        "Environment-gated attack and test penalties from monster traits are not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "attack",
      id: "dagger",
      name: "Dagger",
      text: "*Melee or Ranged Attack Roll:* +4, reach 5 ft. or range 20/60 ft. *Hit:* 4 (1d4 + 2) Piercing damage.",
      attack: {
        name: "Dagger",
        attackBonus: 4,
        reach: 5,
        rangeNormal: 20,
        rangeLong: 60,
        damageAmount: 4,
        damageType: "piercing",
        isRanged: false,
        attackMode: "meleeOrRanged",
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const MAGE = {
  provenance: {
    edition: "SRD 5.2.1",
    document: M_TO_O_SOURCE_DOCUMENT,
    section: "Mage",
  },
  name: "Mage",
  creatureType: "humanoid",
  descriptiveTags: ["Wizard"],
  creatureSize: "medium",
  ac: armorClass(15),
  initiativeMod: abilityModifier(2),
  maxHp: 81,
  hitDice: 18,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 9,
    dex: 14,
    con: 11,
    int: 17,
    wis: 12,
    cha: 11,
  },
  saveProficiencies: new Set(["int", "wis"]),
  skillBonuses: monsterSkillBonuses({
    arcana: 6,
    history: 6,
    perception: 4,
  }),
  cr: { type: "CRN", value: 6 },
  proficiencyBonus: 3,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 14,
  languages: ["Common plus three other languages"],
  gear: ["Wand"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The mage makes three Arcane Burst attacks.",
      slots: [
        { type: "MAttack", name: "Arcane Burst" },
        { type: "MAttack", name: "Arcane Burst" },
        { type: "MAttack", name: "Arcane Burst" },
      ],
    },
    {
      kind: "attack",
      id: "arcaneBurst",
      name: "Arcane Burst",
      text: "*Melee or Ranged Attack Roll:* +6, reach 5 ft. or range 120 ft. *Hit:* 16 (3d8 + 3) Force damage.",
      attack: {
        name: "Arcane Burst",
        attackBonus: 6,
        reach: 5,
        rangeNormal: 120,
        rangeLong: 120,
        damageAmount: 16,
        damageType: "force",
        isRanged: false,
        attackMode: "meleeOrRanged",
      },
    },
    {
      kind: "spellcasting",
      id: "spellcasting",
      name: "Spellcasting",
      text: "The mage casts one of the following spells, using Intelligence as the spellcasting ability (spell save DC 14).",
      spellcastingAbility: "int",
      saveDc: 14,
      spells: [
        { name: "Detect Magic", usage: "At Will" },
        { name: "Light", usage: "At Will" },
        { name: "Mage Armor", usage: "At Will", notes: "included in AC" },
        { name: "Mage Hand", usage: "At Will" },
        { name: "Prestidigitation", usage: "At Will" },
        { name: "Fireball", usage: "2/Day Each", level: 4 },
        { name: "Invisibility", usage: "2/Day Each" },
        { name: "Cone of Cold", usage: "1/Day Each" },
        { name: "Fly", usage: "1/Day Each" },
      ],
    },
  ],
  bonusActions: [
    {
      kind: "spellcasting",
      id: "mistyStep",
      name: "Misty Step",
      text: "The mage casts *Misty Step*, using the same spellcasting ability as Spellcasting.",
      spellcastingAbility: "int",
      spells: [{ name: "Misty Step", usage: "3/Day" }],
    },
  ],
  reactions: [
    {
      kind: "spellcasting",
      id: "protectiveMagic",
      name: "Protective Magic",
      text: "The mage casts *Counterspell* or *Shield* in response to the spell's trigger, using the same spellcasting ability as Spellcasting.",
      spellcastingAbility: "int",
      spells: [
        { name: "Counterspell", usage: "3/Day" },
        { name: "Shield", usage: "3/Day" },
      ],
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
