import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass, spellId } from "#/types.ts";

const M_TO_O_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-M-O.md";
const P_TO_S_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-P-S.md";

export const OGRE = {
  provenance: srdRulesProvenance(M_TO_O_SOURCE_DOCUMENT, "Ogre"),
  name: "Ogre",
  creatureType: "giant",
  creatureSize: "large",
  ac: armorClass(11),
  initiativeMod: abilityModifier(-1),
  maxHp: 68,
  hitDice: 8,
  hitDieType: 10,
  speeds: monsterSpeeds({ walk: 40 }),
  abilityScores: {
    str: 19,
    dex: 8,
    con: 16,
    int: 5,
    wis: 7,
    cha: 7,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CRN", value: 2 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({ darkvision: 60 }),
  passivePerception: 8,
  languages: ["Common", "Giant"],
  gear: ["Greatclub", "Javelins (3)"],
  traits: [],
  actions: [
    {
      kind: "attack",
      id: "greatclub",
      name: "Greatclub",
      text: "*Melee Attack Roll:* +6, reach 5 ft. *Hit:* 13 (2d8 + 4) Bludgeoning damage.",
      attack: {
        name: "Greatclub",
        attackBonus: 6,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 13,
        damageType: "bludgeoning",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "attack",
      id: "javelin",
      name: "Javelin",
      text: "*Melee or Ranged Attack Roll:* +6, reach 5 ft. or range 30/120 ft. *Hit:* 11 (2d6 + 4) Piercing damage.",
      attack: {
        name: "Javelin",
        attackBonus: 6,
        reach: 5,
        rangeNormal: 30,
        rangeLong: 120,
        damageAmount: 11,
        damageType: "piercing",
        isRanged: false,
        attackMode: "meleeOrRanged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const PRIEST = {
  provenance: srdRulesProvenance(P_TO_S_SOURCE_DOCUMENT, "Priests > Priest"),
  name: "Priest",
  creatureType: "humanoid",
  descriptiveTags: ["Cleric"],
  creatureSize: "medium",
  ac: armorClass(13),
  initiativeMod: abilityModifier(0),
  maxHp: 38,
  hitDice: 7,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 16,
    dex: 10,
    con: 12,
    int: 13,
    wis: 16,
    cha: 13,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    medicine: 7,
    perception: 5,
    religion: 5,
  }),
  cr: { type: "CRN", value: 2 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 15,
  languages: ["Common plus one other language"],
  gear: ["Chain Shirt", "Holy Symbol", "Mace"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The priest makes two attacks, using Mace or Radiant Flame in any combination.",
      slots: [
        { type: "MSpecialAbility", name: "Mace" },
        { type: "MAttack", name: "Radiant Flame" },
      ],
    },
    {
      kind: "text",
      id: "mace",
      name: "Mace",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 6 (1d6 + 3) Bludgeoning damage plus 5 (2d4) Radiant damage.",
      nonExecutableReason:
        "Mixed-damage melee spell-weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
    {
      kind: "attack",
      id: "radiantFlame",
      name: "Radiant Flame",
      text: "*Ranged Attack Roll:* +5, range 60 ft. *Hit:* 11 (2d10) Radiant damage.",
      attack: {
        name: "Radiant Flame",
        attackBonus: 5,
        reach: 0,
        rangeNormal: 60,
        rangeLong: 60,
        damageAmount: 11,
        damageType: "radiant",
        isRanged: true,
        attackMode: "ranged",
      },
    },
    {
      kind: "spellcasting",
      id: "spellcasting",
      name: "Spellcasting",
      text: "The priest casts one of the following spells, using Wisdom as the spellcasting ability (spell save DC 13).",
      spellcastingAbility: "wis",
      saveDc: 13,
      spells: [
        { spellId: spellId("light"), usage: "At Will" },
        { spellId: spellId("thaumaturgy"), usage: "At Will" },
        { spellId: spellId("spirit_guardians"), usage: "1/Day" },
      ],
    },
  ],
  bonusActions: [
    {
      kind: "spellcasting",
      id: "divineAid",
      name: "Divine Aid",
      text: "The priest casts *Bless*, *Dispel Magic*, *Healing Word*, or *Lesser Restoration*, using the same spellcasting ability as Spellcasting.",
      spellcastingAbility: "wis",
      spells: [
        { spellId: spellId("bless"), usage: "3/Day" },
        { spellId: spellId("dispel_magic"), usage: "3/Day" },
        { spellId: spellId("healing_word"), usage: "3/Day" },
        { spellId: spellId("lesser_restoration"), usage: "3/Day" },
      ],
    },
  ],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const SAHUAGIN_WARRIOR = {
  provenance: srdRulesProvenance(
    P_TO_S_SOURCE_DOCUMENT,
    "Sahuagin > Sahuagin Warrior",
  ),
  name: "Sahuagin Warrior",
  creatureType: "fiend",
  creatureSize: "medium",
  ac: armorClass(12),
  initiativeMod: abilityModifier(0),
  maxHp: 22,
  hitDice: 4,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30, swim: 40 }),
  abilityScores: {
    str: 13,
    dex: 11,
    con: 12,
    int: 12,
    wis: 13,
    cha: 9,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({ perception: 5 }),
  cr: { type: "CR_Half" },
  proficiencyBonus: 2,
  resistances: new Set(["acid", "cold"]),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({ darkvision: 120 }),
  passivePerception: 15,
  languages: ["Sahuagin"],
  traits: [
    {
      kind: "text",
      id: "bloodFrenzy",
      name: "Blood Frenzy",
      text: "The sahuagin has Advantage on attack rolls against any creature that doesn't have all its Hit Points.",
      nonExecutableReason:
        "Current battle state does not expose a generic wounded-target attack-advantage facility for monster traits.",
    },
    {
      kind: "text",
      id: "limitedAmphibiousness",
      name: "Limited Amphibiousness",
      text: "The sahuagin can breathe air and water, but it must be submerged at least once every 4 hours to avoid suffocating outside water.",
      nonExecutableReason:
        "Long-horizon environmental suffocation constraints are out of scope for the current monster runtime surface.",
    },
    {
      kind: "text",
      id: "sharkTelepathy",
      name: "Shark Telepathy",
      text: "The sahuagin can magically control sharks within 120 feet of itself, using a special telepathy.",
      nonExecutableReason:
        "Monster-command relationships for external allied creatures are not yet modeled on the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The sahuagin makes two Claw attacks.",
      slots: [
        { type: "MAttack", name: "Claw" },
        { type: "MAttack", name: "Claw" },
      ],
    },
    {
      kind: "attack",
      id: "claw",
      name: "Claw",
      text: "*Melee Attack Roll:* +3, reach 5 ft. *Hit:* 4 (1d6 + 1) Slashing damage.",
      attack: {
        name: "Claw",
        attackBonus: 3,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 4,
        damageType: "slashing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: {
          kind: "naturalWeapon",
          damageDie: 6,
          properties: [],
        },
      },
    },
  ],
  bonusActions: [
    {
      kind: "text",
      id: "aquaticCharge",
      name: "Aquatic Charge",
      text: "The sahuagin swims up to its Swim Speed straight toward an enemy it can see.",
      nonExecutableReason:
        "Monster-only bonus-action movement without an attached generic attack or save effect is not yet projected into the generic monster runtime surface.",
    },
  ],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const SCOUT = {
  provenance: srdRulesProvenance(P_TO_S_SOURCE_DOCUMENT, "Scout"),
  name: "Scout",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(13),
  initiativeMod: abilityModifier(2),
  maxHp: 16,
  hitDice: 3,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 11,
    dex: 14,
    con: 12,
    int: 11,
    wis: 13,
    cha: 11,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    nature: 4,
    perception: 5,
    stealth: 6,
    survival: 5,
  }),
  cr: { type: "CR_Half" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 15,
  languages: ["Common plus one other language"],
  gear: ["Leather Armor", "Longbow", "Shortsword"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The scout makes two attacks, using Shortsword and Longbow in any combination.",
      slots: [
        { type: "MAttack", name: "Shortsword" },
        { type: "MAttack", name: "Longbow" },
      ],
    },
    {
      kind: "attack",
      id: "shortsword",
      name: "Shortsword",
      text: "*Melee Attack Roll:* +4, reach 5 ft. *Hit:* 5 (1d6 + 2) Piercing damage.",
      attack: {
        name: "Shortsword",
        attackBonus: 4,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 5,
        damageType: "piercing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "attack",
      id: "longbow",
      name: "Longbow",
      text: "*Ranged Attack Roll:* +4, range 150/600 ft. *Hit:* 6 (1d8 + 2) Piercing damage.",
      attack: {
        name: "Longbow",
        attackBonus: 4,
        reach: 0,
        rangeNormal: 150,
        rangeLong: 600,
        damageAmount: 6,
        damageType: "piercing",
        isRanged: true,
        attackMode: "ranged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
