import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass, spellId } from "#/types.ts";

const C_TO_D_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-C-D.md";

export const COMMONER = {
  provenance: srdRulesProvenance(C_TO_D_SOURCE_DOCUMENT, "Commoner"),
  name: "Commoner",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(10),
  initiativeMod: abilityModifier(0),
  maxHp: 4,
  hitDice: 1,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    cha: 10,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CR0" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common"],
  gear: ["Club"],
  traits: [
    {
      kind: "text",
      id: "training",
      name: "Training",
      text: "The commoner has proficiency in one skill of the GM's choice and has Advantage whenever it makes an ability check using that skill.",
      nonExecutableReason:
        "GM-chosen skill proficiency and ability-check advantage are not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "attack",
      id: "club",
      name: "Club",
      text: "*Melee Attack Roll:* +2, reach 5 ft. *Hit:* 2 (1d4) Bludgeoning damage.",
      attack: {
        name: "Club",
        attackBonus: 2,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 2,
        damageType: "bludgeoning",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const CULTIST = {
  provenance: srdRulesProvenance(C_TO_D_SOURCE_DOCUMENT, "Cultists > Cultist"),
  name: "Cultist",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(12),
  initiativeMod: abilityModifier(1),
  maxHp: 9,
  hitDice: 2,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 11,
    dex: 12,
    con: 10,
    int: 10,
    wis: 11,
    cha: 10,
  },
  saveProficiencies: new Set(["wis"]),
  skillBonuses: monsterSkillBonuses({
    deception: 2,
    religion: 2,
  }),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common"],
  gear: ["Leather Armor", "Sickle"],
  traits: [],
  actions: [
    {
      kind: "text",
      id: "ritualSickle",
      name: "Ritual Sickle",
      text: "*Melee Attack Roll:* +3, reach 5 ft. *Hit:* 3 (1d4 + 1) Slashing damage plus 1 Necrotic damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const CULTIST_FANATIC = {
  provenance: srdRulesProvenance(
    C_TO_D_SOURCE_DOCUMENT,
    "Cultists > Cultist Fanatic",
  ),
  name: "Cultist Fanatic",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(13),
  initiativeMod: abilityModifier(2),
  maxHp: 44,
  hitDice: 8,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 11,
    dex: 14,
    con: 12,
    int: 10,
    wis: 14,
    cha: 13,
  },
  saveProficiencies: new Set(["wis"]),
  skillBonuses: monsterSkillBonuses({
    deception: 3,
    persuasion: 3,
    religion: 2,
  }),
  cr: { type: "CRN", value: 2 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 12,
  languages: ["Common"],
  gear: ["Holy Symbol", "Leather Armor"],
  traits: [],
  actions: [
    {
      kind: "text",
      id: "pactBlade",
      name: "Pact Blade",
      text: "*Melee Attack Roll:* +4, reach 5 ft. *Hit:* 6 (1d8 + 2) Slashing damage plus 7 (2d6) Necrotic damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
    {
      kind: "spellcasting",
      id: "spellcasting",
      name: "Spellcasting",
      text: "The cultist casts one of the following spells, using Wisdom as the spellcasting ability (spell save DC 12, +4 to hit with spell attacks):",
      spellcastingAbility: "wis",
      saveDc: 12,
      attackBonus: 4,
      spells: [
        { spellId: spellId("light"), usage: "At Will" },
        { spellId: spellId("thaumaturgy"), usage: "At Will" },
        { spellId: spellId("command"), usage: "2/Day" },
        { spellId: spellId("hold_person"), usage: "1/Day" },
      ],
    },
  ],
  bonusActions: [
    {
      kind: "spellcasting",
      id: "spiritualWeapon",
      name: "Spiritual Weapon",
      text: "The cultist casts the *Spiritual Weapon* spell, using the same spellcasting ability as Spellcasting.",
      spellcastingAbility: "wis",
      spells: [{ spellId: spellId("spiritual_weapon"), usage: "2/Day" }],
    },
  ],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
