import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass } from "#/types.ts";

const A_TO_B_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-A-B.md";

export const BANDIT = {
  provenance: srdRulesProvenance(A_TO_B_SOURCE_DOCUMENT, "Bandits > Bandit"),
  name: "Bandit",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(12),
  initiativeMod: abilityModifier(1),
  maxHp: 11,
  hitDice: 2,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 11,
    dex: 12,
    con: 12,
    int: 10,
    wis: 10,
    cha: 10,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common", "Thieves' Cant"],
  gear: ["Leather Armor", "Light Crossbow", "Scimitar"],
  traits: [],
  actions: [
    {
      kind: "attack",
      id: "scimitar",
      name: "Scimitar",
      text: "*Melee Attack Roll:* +3, reach 5 ft. *Hit:* 4 (1d6 + 1) Slashing damage.",
      attack: {
        name: "Scimitar",
        attackBonus: 3,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 4,
        damageType: "slashing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "attack",
      id: "lightCrossbow",
      name: "Light Crossbow",
      text: "*Ranged Attack Roll:* +3, range 80/320 ft. *Hit:* 5 (1d8 + 1) Piercing damage.",
      attack: {
        name: "Light Crossbow",
        attackBonus: 3,
        reach: 0,
        rangeNormal: 80,
        rangeLong: 320,
        damageAmount: 5,
        damageType: "piercing",
        isRanged: true,
        attackMode: "ranged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const BANDIT_CAPTAIN = {
  provenance: srdRulesProvenance(
    A_TO_B_SOURCE_DOCUMENT,
    "Bandits > Bandit Captain",
  ),
  name: "Bandit Captain",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(15),
  initiativeMod: abilityModifier(3),
  maxHp: 52,
  hitDice: 8,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 15,
    dex: 16,
    con: 14,
    int: 14,
    wis: 11,
    cha: 14,
  },
  saveProficiencies: new Set(["str"]),
  skillBonuses: monsterSkillBonuses({
    athletics: 4,
    deception: 4,
  }),
  cr: { type: "CRN", value: 2 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common", "Thieves' Cant"],
  gear: ["Pistol", "Scimitar", "Studded Leather Armor"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The bandit makes two attacks, using Scimitar and Pistol in any combination.",
      slots: [
        { type: "MAttack", name: "Scimitar" },
        { type: "MAttack", name: "Pistol" },
      ],
    },
    {
      kind: "attack",
      id: "scimitar",
      name: "Scimitar",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 6 (1d6 + 3) Slashing damage.",
      attack: {
        name: "Scimitar",
        attackBonus: 5,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 6,
        damageType: "slashing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "attack",
      id: "pistol",
      name: "Pistol",
      text: "*Ranged Attack Roll:* +5, range 30/90 ft. *Hit:* 8 (1d10 + 3) Piercing damage.",
      attack: {
        name: "Pistol",
        attackBonus: 5,
        reach: 0,
        rangeNormal: 30,
        rangeLong: 90,
        damageAmount: 8,
        damageType: "piercing",
        isRanged: true,
        attackMode: "ranged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [
    {
      kind: "text",
      id: "parry",
      name: "Parry",
      text: "*Trigger:* The bandit is hit by a melee attack roll while holding a weapon. *Response:* The bandit adds 2 to its AC against that attack, possibly causing it to miss.",
      nonExecutableReason:
        "Reactive AC boosts are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const BERSERKER = {
  provenance: srdRulesProvenance(A_TO_B_SOURCE_DOCUMENT, "Berserker"),
  name: "Berserker",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(13),
  initiativeMod: abilityModifier(1),
  maxHp: 67,
  hitDice: 9,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 16,
    dex: 12,
    con: 17,
    int: 9,
    wis: 11,
    cha: 9,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CRN", value: 2 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 10,
  languages: ["Common"],
  gear: ["Greataxe", "Hide Armor"],
  traits: [
    {
      kind: "text",
      id: "bloodiedFrenzy",
      name: "Bloodied Frenzy",
      text: "While Bloodied, the berserker has Advantage on attack rolls and saving throws.",
      nonExecutableReason:
        "Bloodied-gated attack and saving-throw advantage from monster traits is not yet projected into the generic monster runtime surface.",
    },
  ],
  actions: [
    {
      kind: "attack",
      id: "greataxe",
      name: "Greataxe",
      text: "*Melee Attack Roll:* +5, reach 5 ft. *Hit:* 9 (1d12 + 3) Slashing damage.",
      attack: {
        name: "Greataxe",
        attackBonus: 5,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 9,
        damageType: "slashing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
