import {
  monsterSenses,
  monsterSkillBonuses,
  monsterSpeeds,
  srdRulesProvenance,
} from "#/monster-catalog-helpers.ts";
import { type StatBlock } from "#/monster-types.ts";
import { abilityModifier, armorClass } from "#/types.ts";

const M_TO_O_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-M-O.md";
const P_TO_S_SOURCE_DOCUMENT = ".references/srd-5.2.1/Monsters/Monsters-P-S.md";

export const NOBLE = {
  provenance: srdRulesProvenance(M_TO_O_SOURCE_DOCUMENT, "Noble"),
  name: "Noble",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(15),
  initiativeMod: abilityModifier(1),
  maxHp: 9,
  hitDice: 2,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 11,
    dex: 12,
    con: 11,
    int: 12,
    wis: 14,
    cha: 16,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    deception: 5,
    insight: 4,
    persuasion: 5,
  }),
  cr: { type: "CR_Eighth" },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 12,
  languages: ["Common plus two other languages"],
  gear: ["Breastplate", "Rapier"],
  traits: [],
  actions: [
    {
      kind: "attack",
      id: "rapier",
      name: "Rapier",
      text: "*Melee Attack Roll:* +3, reach 5 ft. *Hit:* 5 (1d8 + 1) Piercing damage.",
      attack: {
        name: "Rapier",
        attackBonus: 3,
        reach: 5,
        rangeNormal: 0,
        rangeLong: 0,
        damageAmount: 5,
        damageType: "piercing",
        isRanged: false,
        attackMode: "melee",
        battleProfile: { kind: "stockWeapon" },
      },
    },
  ],
  bonusActions: [],
  reactions: [
    {
      kind: "text",
      id: "parry",
      name: "Parry",
      text: "*Trigger:* The noble is hit by a melee attack roll while holding a weapon. *Response:* The noble adds 2 to its AC against that attack, possibly causing it to miss.",
      nonExecutableReason:
        "Reactive AC boosts are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const PIRATE = {
  provenance: srdRulesProvenance(P_TO_S_SOURCE_DOCUMENT, "Pirates > Pirate"),
  name: "Pirate",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(14),
  initiativeMod: abilityModifier(5),
  maxHp: 33,
  hitDice: 6,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 10,
    dex: 16,
    con: 12,
    int: 8,
    wis: 12,
    cha: 14,
  },
  saveProficiencies: new Set(["cha"]),
  skillBonuses: monsterSkillBonuses({}),
  cr: { type: "CRN", value: 1 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 11,
  languages: ["Common plus one other language"],
  gear: ["Daggers (6)", "Leather Armor"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The pirate makes two Dagger attacks. It can replace one attack with a use of Enthralling Panache.",
      slots: [
        { type: "MAttack", name: "Dagger" },
        { type: "MSpecialAbility", name: "Enthralling Panache" },
      ],
    },
    {
      kind: "attack",
      id: "dagger",
      name: "Dagger",
      text: "*Melee or Ranged Attack Roll:* +5, reach 5 ft. or range 20/60 ft. *Hit:* 5 (1d4 + 3) Piercing damage.",
      attack: {
        name: "Dagger",
        attackBonus: 5,
        reach: 5,
        rangeNormal: 20,
        rangeLong: 60,
        damageAmount: 5,
        damageType: "piercing",
        isRanged: false,
        attackMode: "meleeOrRanged",
        battleProfile: { kind: "stockWeapon" },
      },
    },
    {
      kind: "text",
      id: "enthrallingPanache",
      name: "Enthralling Panache",
      text: "*Wisdom Saving Throw:* DC 12, one creature the pirate can see within 30 feet. *Failure:* The target has the Charmed condition until the start of the pirate's next turn.",
      nonExecutableReason:
        "Short-duration charm save actions are not yet projected into the generic monster runtime surface.",
    },
  ],
  bonusActions: [],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const PIRATE_CAPTAIN = {
  provenance: srdRulesProvenance(
    P_TO_S_SOURCE_DOCUMENT,
    "Pirates > Pirate Captain",
  ),
  name: "Pirate Captain",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(17),
  initiativeMod: abilityModifier(7),
  maxHp: 84,
  hitDice: 13,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30 }),
  abilityScores: {
    str: 10,
    dex: 18,
    con: 14,
    int: 10,
    wis: 14,
    cha: 17,
  },
  saveProficiencies: new Set(["str", "dex", "wis", "cha"]),
  skillBonuses: monsterSkillBonuses({
    acrobatics: 7,
    perception: 5,
  }),
  cr: { type: "CRN", value: 6 },
  proficiencyBonus: 3,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 15,
  languages: ["Common plus one other language"],
  gear: ["Pistol", "Rapier"],
  traits: [],
  actions: [
    {
      kind: "multiattack",
      id: "multiattack",
      name: "Multiattack",
      text: "The pirate makes three attacks, using Rapier or Pistol in any combination.",
      slots: [
        { type: "MSpecialAbility", name: "Rapier" },
        { type: "MSpecialAbility", name: "Pistol" },
        { type: "MSpecialAbility", name: "Rapier" },
      ],
    },
    {
      kind: "text",
      id: "rapier",
      name: "Rapier",
      text: "*Melee Attack Roll:* +7, reach 5 ft. *Hit:* 13 (2d8 + 4) Piercing damage, and the pirate has Advantage on the next attack roll it makes before the end of this turn.",
      nonExecutableReason:
        "On-hit self-buff attack riders are not yet projected into the generic monster attack surface.",
    },
    {
      kind: "text",
      id: "pistol",
      name: "Pistol",
      text: "*Ranged Attack Roll:* +7, range 30/90 ft. *Hit:* 15 (2d10 + 4) Piercing damage.",
      nonExecutableReason:
        "Stock-weapon attacks whose SRD damage dice do not match the current shared weapon profile stay text-only until a later generic monster attack surface exists.",
    },
  ],
  bonusActions: [
    {
      kind: "text",
      id: "captainsCharm",
      name: "Captain's Charm",
      text: "*Wisdom Saving Throw:* DC 14, one creature the pirate can see within 30 feet. *Failure:* The target has the Charmed condition until the start of the pirate's next turn.",
      nonExecutableReason:
        "Short-duration charm save actions are not yet projected into the generic monster runtime surface.",
    },
  ],
  reactions: [
    {
      kind: "text",
      id: "riposte",
      name: "Riposte",
      text: "*Trigger:* The pirate is hit by a melee attack roll while holding a weapon. *Response:* The pirate adds 3 to its AC against that attack, possibly causing it to miss. On a miss, the pirate makes one Rapier attack against the triggering creature if within range.",
      nonExecutableReason:
        "Reactive AC boosts plus conditional counterattacks are not yet projected into the generic monster runtime surface.",
    },
  ],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;

export const SPY = {
  provenance: srdRulesProvenance(P_TO_S_SOURCE_DOCUMENT, "Spy"),
  name: "Spy",
  creatureType: "humanoid",
  creatureSize: "medium",
  ac: armorClass(12),
  initiativeMod: abilityModifier(4),
  maxHp: 27,
  hitDice: 6,
  hitDieType: 8,
  speeds: monsterSpeeds({ walk: 30, climb: 30 }),
  abilityScores: {
    str: 10,
    dex: 15,
    con: 10,
    int: 12,
    wis: 14,
    cha: 16,
  },
  saveProficiencies: new Set(),
  skillBonuses: monsterSkillBonuses({
    deception: 5,
    insight: 4,
    investigation: 5,
    perception: 6,
    sleightOfHand: 4,
    stealth: 6,
  }),
  cr: { type: "CRN", value: 1 },
  proficiencyBonus: 2,
  resistances: new Set(),
  vulnerabilities: new Set(),
  damageImmunities: new Set(),
  conditionImmunities: new Set(),
  exhaustionImmune: false,
  senses: monsterSenses({}),
  passivePerception: 16,
  languages: ["Common plus one other language"],
  gear: ["Hand Crossbow", "Shortsword", "Thieves' Tools"],
  traits: [],
  actions: [
    {
      kind: "text",
      id: "shortsword",
      name: "Shortsword",
      text: "*Melee Attack Roll:* +4, reach 5 ft. *Hit:* 5 (1d6 + 2) Piercing damage plus 7 (2d6) Poison damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
    {
      kind: "text",
      id: "handCrossbow",
      name: "Hand Crossbow",
      text: "*Ranged Attack Roll:* +4, range 30/120 ft. *Hit:* 5 (1d6 + 2) Piercing damage plus 7 (2d6) Poison damage.",
      nonExecutableReason:
        "Mixed-damage weapon attacks are not yet normalized into the generic monster attack projection surface.",
    },
  ],
  bonusActions: [
    {
      kind: "text",
      id: "cunningAction",
      name: "Cunning Action",
      text: "The spy takes the Dash, Disengage, or Hide action.",
      nonExecutableReason:
        "Bonus-action Dash/Disengage/Hide bundles are not yet projected into the generic monster runtime surface.",
    },
  ],
  reactions: [],
  legendaryActionUses: 0,
  legendaryResistanceUses: 0,
  legendaryActions: [],
  rechargeAbilities: {},
  dailyAbilities: {},
  inLair: false,
} as const satisfies StatBlock;
