export {
  describeElapsedTimeParseError,
  decrementBoundaryCrossingsRemaining,
  boundaryCrossingsRemaining,
  elapsedTimeTicks,
  elapsedTimeTicksFromHours,
  elapsedTimeTicksFromMinutes,
  elapsedTimeTicksFromTimeSpanDuration,
  elapsedTimeTicksFromUnit,
  ELAPSED_TIME_HOURS_PER_DAY,
  ELAPSED_TIME_TICKS_PER_DAY,
  ELAPSED_TIME_TICKS_PER_HOUR,
  ELAPSED_TIME_TICKS_PER_MINUTE,
  TIME_SPAN_SECONDS_PER_ROUND,
  TIME_SPAN_UNITS,
  formatElapsedTimeTicks,
  formatTimeSpanDuration,
  isTimeSpanUnit,
  parseElapsedTimeTicks,
  parsePositiveElapsedTimeTicks,
  parsePositiveInt,
  timeSpanDuration,
  type TimeSpanDuration,
  type ElapsedTimeParseError,
  type ElapsedTimeTicks,
  type PositiveElapsedTimeTicks,
  type TimeSpanUnit,
  type BoundaryCrossingsRemaining,
  type PositiveInt,
  type SurfaceTimeSpanDurationValue,
} from "@dnd/shared/elapsed-time";
