export {
  describeElapsedTimeParseError,
  decrementInitiativeDurationRounds,
  elapsedTimeTicks,
  elapsedTimeTicksFromHours,
  elapsedTimeTicksFromMinutes,
  elapsedTimeTicksFromSurfaceDuration,
  elapsedTimeTicksFromUnit,
  ELAPSED_TIME_HOURS_PER_DAY,
  ELAPSED_TIME_TICKS_PER_DAY,
  ELAPSED_TIME_TICKS_PER_HOUR,
  ELAPSED_TIME_TICKS_PER_MINUTE,
  ELAPSED_TIME_UNITS,
  formatElapsedTimeDuration,
  initiativeDurationRounds,
  initiativeRoundsFromElapsedTimeTicks,
  isElapsedTimeUnit,
  parseElapsedTimeTicks,
  type ElapsedTimeDuration,
  type ElapsedTimeParseError,
  type ElapsedTimeTicks,
  type ElapsedTimeUnit,
  type InitiativeDurationRounds,
  type SurfaceElapsedDurationValue,
} from "@dnd/shared/elapsed-time";
