let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 2, id = "stat_block_allosaurus", kind = "statBlock", name = "Allosaurus", provenance = { kind = "srd-5.2.1", section = "Animals.md:3-25" }, statBlock = { abilityScores = { cha = 5, con = 17, dex = 13, int = 2, str = 19, wis = 12 }, ac = { value = { kind = "literal", value = 13 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +6 }, attackType = Some "melee", description = Some "*Melee Attack Roll:* +6, reach 5 ft. *Hit:* 15 (2d10 + 4) Piercing damage.", kind = "attack_roll", name = "Bite", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 2, dieSize = 10, flat = Some +4 }, kind = "fixed", static = 15 }, damageType = "piercing" } ], reachFeet = Some 5 } ), procedureOrdinal = 1 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +6 }, attackType = Some "melee", description = Some "*Melee Attack Roll:* +6, reach 5 ft. *Hit:* 8 (1d8 + 4) Slashing damage. If the target is a Large or smaller creature and the allosaurus moved 30+ feet straight toward it immediately before the hit, the target has the Prone condition, and the allosaurus can make one Bite attack against it.", kind = "attack_roll", name = "Claws", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 1, dieSize = 8, flat = Some +4 }, kind = "fixed", static = 8 }, damageType = "slashing" } ], reachFeet = Some 5 } ), procedureOrdinal = 2 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", creatureTypeTags = [ "dinosaur" ], hp = { kind = "literal", value = 51 }, initiative = { modifier = +1, score = 11 }, passivePerception = 15, savingThrowModifiers = [ { ability = "str", modifier = +4 }, { ability = "dex", modifier = +1 }, { ability = "con", modifier = +3 }, { ability = "int", modifier = -4 }, { ability = "wis", modifier = +1 }, { ability = "cha", modifier = -3 } ], size = "large", skillModifiers = [ { modifier = +5, skill = "perception" } ], speeds = [ { feet = { kind = "literal", value = 60 }, kind = "walk" } ] } }




