let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 0, id = "stat_block_goat", kind = "statBlock", name = "Goat", provenance = { kind = "srd-5.2.1", section = "Animals.md:1430-1450" }, statBlock = { abilityScores = { cha = 5, con = 11, dex = 10, int = 2, str = 11, wis = 10 }, ac = { value = { kind = "literal", value = 10 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +2, reach 5 ft. *Hit:* 1 Bludgeoning damage, or 2 (1d4) Bludgeoning damage if the goat moved 20+ feet straight toward the target immediately before the hit.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +2 }, attackType = Some "melee", kind = "attack_roll", name = "Ram", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 1, dieSize = 4, flat = None Integer }, kind = "fixed", static = 2 }, damageType = "bludgeoning" } ], reachFeet = Some 5 } ), procedureOrdinal = 1 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 4 }, initiative = { modifier = +0, score = 10 }, passivePerception = 12, savingThrowModifiers = [ { ability = "str", modifier = +2 }, { ability = "dex", modifier = +0 }, { ability = "con", modifier = +0 }, { ability = "int", modifier = -4 }, { ability = "wis", modifier = +0 }, { ability = "cha", modifier = -3 } ], senses = [ { kind = "darkvision", rangeFeet = 60 } ], size = "medium", skillModifiers = [ { modifier = +2, skill = "perception" } ], speeds = [ { feet = { kind = "literal", value = 40 }, kind = "walk" }, { feet = { kind = "literal", value = 30 }, kind = "climb" } ] } }





