let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 5, id = "stat_block_giant_shark", kind = "statBlock", name = "Giant Shark", provenance = { kind = "srd-5.2.1", section = "Animals.md:1205-1231" }, statBlock = { abilityScores = { cha = 5, con = 21, dex = 11, int = 1, str = 23, wis = 10 }, ac = { value = { kind = "literal", value = 13 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { dispatches = Some [ { count = { kind = "literal", value = +2 }, procedureOrdinal = 2 } ], kind = "multiattack", name = "Multiattack" }), procedureOrdinal = 1 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +9 (with Advantage if the target doesn't have all its Hit Points), reach 5 ft. *Hit:* 22 (3d10 + 6) Piercing damage.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +9 }, attackType = Some "melee", kind = "attack_roll", name = "Bite", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 3, dieSize = 10, flat = Some +6 }, kind = "fixed", static = 22 }, damageType = "piercing" } ], reachFeet = Some 5 } ), procedureOrdinal = 2 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 92 }, initiative = { modifier = +3, score = 13 }, passivePerception = 13, savingThrowModifiers = [ { ability = "str", modifier = +6 }, { ability = "dex", modifier = +0 }, { ability = "con", modifier = +5 }, { ability = "int", modifier = -5 }, { ability = "wis", modifier = +0 }, { ability = "cha", modifier = -3 } ], senses = [ { kind = "blindsight", rangeFeet = 60 } ], size = "huge", skillModifiers = [ { modifier = +3, skill = "perception" } ], speeds = [ { feet = { kind = "literal", value = 5 }, kind = "walk" }, { feet = { kind = "literal", value = 60 }, kind = "swim" } ], traits = [ { description = "The shark can breathe only underwater.", name = "Water Breathing" } ] } }



