let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 1, id = "stat_block_giant_octopus", kind = "statBlock", name = "Giant Octopus", provenance = { kind = "srd-5.2.1", section = "Animals.md:1053-1081" }, statBlock = { abilityScores = { cha = 4, con = 13, dex = 13, int = 5, str = 17, wis = 10 }, ac = { value = { kind = "literal", value = 11 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +5, reach 10 ft. *Hit:* 10 (2d6 + 3) Bludgeoning damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13) from all eight tentacles. While Grappled, the target has the Restrained condition.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +5 }, attackType = Some "melee", kind = "attack_roll", name = "Tentacles", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 2, dieSize = 6, flat = Some +3 }, kind = "fixed", static = 10 }, damageType = "bludgeoning" } ], reachFeet = Some 10 } ), procedureOrdinal = 1 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 45 }, initiative = { modifier = +1, score = 11 }, passivePerception = 14, savingThrowModifiers = [ { ability = "str", modifier = +3 }, { ability = "dex", modifier = +1 }, { ability = "con", modifier = +1 }, { ability = "int", modifier = -3 }, { ability = "wis", modifier = -4 }, { ability = "cha", modifier = -3 } ], senses = [ { kind = "darkvision", rangeFeet = 60 } ], size = "large", skillModifiers = [ { modifier = +4, skill = "perception" }, { modifier = +5, skill = "stealth" } ], speeds = [ { feet = { kind = "literal", value = 10 }, kind = "walk" }, { feet = { kind = "literal", value = 60 }, kind = "swim" } ], traits = [ { description = "The octopus can breathe only underwater. It can hold its breath for 1 hour outside water.", name = "Water Breathing" } ] } }





