let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 8, id = "stat_block_tyrannosaurus_rex", kind = "statBlock", name = "Tyrannosaurus Rex", provenance = { kind = "srd-5.2.1", section = "Animals.md:2461-2485" }, statBlock = { abilityScores = { cha = 9, con = 19, dex = 10, int = 2, str = 25, wis = 12 }, ac = { value = { kind = "literal", value = 13 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { dispatches = Some [ { count = { kind = "literal", value = +1 }, procedureOrdinal = 2 }, { count = { kind = "literal", value = +1 }, procedureOrdinal = 3 } ], kind = "multiattack", name = "Multiattack" }), procedureOrdinal = 1 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +10, reach 10 ft. *Hit:* 33 (4d12 + 7) Piercing damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 17). While Grappled, the target has the Restrained condition and can't be targeted by the tyrannosaurus's Tail.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +10 }, attackType = Some "melee", kind = "attack_roll", name = "Bite", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 4, dieSize = 12, flat = Some +7 }, kind = "fixed", static = 33 }, damageType = "piercing" } ], reachFeet = Some 10 } ), procedureOrdinal = 2 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +10, reach 15 ft. *Hit:* 25 (4d8 + 7) Bludgeoning damage. If the target is a Huge or smaller creature, it has the Prone condition.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +10 }, attackType = Some "melee", kind = "attack_roll", name = "Tail", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 4, dieSize = 8, flat = Some +7 }, kind = "fixed", static = 25 }, damageType = "bludgeoning" } ], reachFeet = Some 15 } ), procedureOrdinal = 3 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", creatureTypeTags = [ "dinosaur" ], hp = { kind = "literal", value = 136 }, initiative = { modifier = +3, score = 13 }, passivePerception = 14, savingThrowModifiers = [ { ability = "str", modifier = +10 }, { ability = "dex", modifier = +0 }, { ability = "con", modifier = +4 }, { ability = "int", modifier = -4 }, { ability = "wis", modifier = +4 }, { ability = "cha", modifier = -1 } ], size = "huge", skillModifiers = [ { modifier = +4, skill = "perception" } ], speeds = [ { feet = { kind = "literal", value = 50 }, kind = "walk" } ] } }



