let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 0.25, id = "stat_block_giant_owl", kind = "statBlock", name = "Giant Owl", provenance = { kind = "srd-5.2.1", section = "Animals.md:1085-1115" }, statBlock = { abilityScores = { cha = 10, con = 12, dex = 15, int = 10, str = 13, wis = 14 }, ac = { value = { kind = "literal", value = 12 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +4, reach 5 ft. *Hit:* 7 (1d10 + 2) Slashing damage.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +4 }, attackType = Some "melee", kind = "attack_roll", name = "Talons", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 1, dieSize = 10, flat = Some +2 }, kind = "fixed", static = 7 }, damageType = "slashing" } ], reachFeet = Some 5 } ), procedureOrdinal = 1 }, defaultAction // { description = Some "The owl casts one of the following spells, requiring no spell components and using Wisdom as the spellcasting ability:", kind = "textOnly", name = Some "Spellcasting", procedureOrdinal = 2, reason = Some "unsupported_procedure_family" } ], alignment = { morality = "neutral", order = "neutral" }, communication = { kind = "understood_but_cannot_speak", languages = { kind = "named", languages = [ "Celestial", "Common", "Elvish", "Sylvan" ] } }, creatureType = "celestial", hp = { kind = "literal", value = 19 }, initiative = { modifier = +2, score = 12 }, passivePerception = 16, resistances = { damageTypes = [ "necrotic", "radiant" ], kind = "fixed" }, savingThrowModifiers = [ { ability = "str", modifier = +1 }, { ability = "dex", modifier = +2 }, { ability = "con", modifier = +1 }, { ability = "int", modifier = +0 }, { ability = "wis", modifier = +4 }, { ability = "cha", modifier = +0 } ], senses = [ { kind = "darkvision", rangeFeet = 120 } ], size = "large", skillModifiers = [ { modifier = +6, skill = "perception" }, { modifier = +6, skill = "stealth" } ], speeds = [ { feet = { kind = "literal", value = 5 }, kind = "walk" }, { feet = { kind = "literal", value = 60 }, kind = "fly" } ], traits = [ { description = "The owl doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.", name = "Flyby" } ] } }





