let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 7, id = "stat_block_giant_ape", kind = "statBlock", name = "Giant Ape", provenance = { kind = "srd-5.2.1", section = "Animals.md:642-670" }, statBlock = { abilityScores = { cha = 7, con = 18, dex = 14, int = 5, str = 23, wis = 12 }, ac = { value = { kind = "literal", value = 12 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { dispatches = Some [ { count = { kind = "literal", value = +2 }, procedureOrdinal = 2 } ], kind = "multiattack", name = "Multiattack" }), procedureOrdinal = 1 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +9, reach 10 ft. *Hit:* 22 (3d10 + 6) Bludgeoning damage.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +9 }, attackType = Some "melee", kind = "attack_roll", name = "Fist", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 3, dieSize = 10, flat = Some +6 }, kind = "fixed", static = 22 }, damageType = "bludgeoning" } ], reachFeet = Some 10 } ), procedureOrdinal = 2 }, defaultAction // { description = Some "The ape hurls a boulder at a point it can see within 90 feet. *Dexterity Saving Throw:* DC 17, each creature in a 5-foot-radius Sphere centered on that point. *Failure:* 24 (7d6) Bludgeoning damage. If the target is a Large or smaller creature, it has the Prone condition. *Success:* Half damage only.", kind = "textOnly", name = Some "Boulder Toss (Recharge 6)", procedureOrdinal = 3, reason = Some "unsupported_procedure_family" } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 168 }, initiative = { modifier = +5, score = 15 }, passivePerception = 14, savingThrowModifiers = [ { ability = "str", modifier = +6 }, { ability = "dex", modifier = +2 }, { ability = "con", modifier = +4 }, { ability = "int", modifier = -3 }, { ability = "wis", modifier = +1 }, { ability = "cha", modifier = -2 } ], size = "huge", skillModifiers = [ { modifier = +9, skill = "athletics" }, { modifier = +4, skill = "perception" }, { modifier = +4, skill = "survival" } ], speeds = [ { feet = { kind = "literal", value = 40 }, kind = "walk" }, { feet = { kind = "literal", value = 40 }, kind = "climb" } ] } }



