let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 2, id = "stat_block_saber_toothed_tiger", kind = "statBlock", name = "Saber-Toothed Tiger", provenance = { kind = "srd-5.2.1", section = "Animals.md:2112-2142" }, statBlock = { abilityScores = { cha = 8, con = 15, dex = 17, int = 3, str = 18, wis = 12 }, ac = { value = { kind = "literal", value = 13 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { dispatches = Some [ { count = { kind = "literal", value = +2 }, procedureOrdinal = 2 } ], kind = "multiattack", name = "Multiattack" }), procedureOrdinal = 1 }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +6, reach 5 ft. *Hit:* 11 (2d6 + 4) Slashing damage.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +6 }, attackType = Some "melee", kind = "attack_roll", name = "Rend", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 2, dieSize = 6, flat = Some +4 }, kind = "fixed", static = 11 }, damageType = "slashing" } ], reachFeet = Some 5 } ), procedureOrdinal = 2 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 52 }, initiative = { modifier = +3, score = 13 }, passivePerception = 15, savingThrowModifiers = [ { ability = "str", modifier = +6 }, { ability = "dex", modifier = +5 }, { ability = "con", modifier = +2 }, { ability = "int", modifier = -4 }, { ability = "wis", modifier = +1 }, { ability = "cha", modifier = -1 } ], senses = [ { kind = "darkvision", rangeFeet = 60 } ], size = "large", skillModifiers = [ { modifier = +5, skill = "perception" }, { modifier = +7, skill = "stealth" } ], speeds = [ { feet = { kind = "literal", value = 40 }, kind = "walk" } ], traits = [ { description = "With a 10-foot running start, the tiger can Long Jump up to 25 feet.", name = "Running Leap" } ] } }



