let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 0.5, id = "stat_block_swarm_of_insects", kind = "statBlock", name = "Swarm of Insects", provenance = { kind = "srd-5.2.1", section = "Animals.md:2256-2283" }, statBlock = { abilityScores = { cha = 1, con = 14, dex = 13, int = 1, str = 3, wis = 7 }, ac = { value = { kind = "literal", value = 11 } }, actions = [ defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +3, reach 5 ft. *Hit:* 6 (2d4 + 1) Poison damage, or 3 (1d4 + 1) Poison damage if the swarm is Bloodied.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +3 }, attackType = Some "melee", kind = "attack_roll", name = "Bites", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 2, dieSize = 4, flat = Some +1 }, kind = "fixed", static = 6 }, damageType = "poison" } ], reachFeet = Some 5 } ), procedureOrdinal = 1 } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", creatureTypeTags = [ "swarm of tiny beasts" ], hp = { kind = "literal", value = 19 }, immunities = { conditions = [ "charmed", "frightened", "grappled", "paralyzed", "petrified", "prone", "restrained", "stunned" ] }, initiative = { modifier = +1, score = 11 }, passivePerception = 8, resistances = { damageTypes = [ "bludgeoning", "piercing", "slashing" ], kind = "fixed" }, savingThrowModifiers = [ { ability = "str", modifier = -4 }, { ability = "dex", modifier = +1 }, { ability = "con", modifier = +2 }, { ability = "int", modifier = -5 }, { ability = "wis", modifier = -2 }, { ability = "cha", modifier = -5 } ], senses = [ { kind = "blindsight", rangeFeet = 30 } ], size = "medium", speeds = [ { feet = { kind = "literal", value = 20 }, kind = "walk" }, { feet = { kind = "literal", value = 20 }, kind = "climb" }, { feet = { kind = "literal", value = 20 }, kind = "fly" } ], traits = [ { description = "If the swarm has a Climb Speed, the swarm can climb difficult surfaces, including along ceilings, without needing to make an ability check.", name = "Spider Climb" }, { description = "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny insect. The swarm can't regain Hit Points or gain Temporary Hit Points.", name = "Swarm" } ] } }





