let Effect : Type = { amount : { expr : Optional { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind : Text, static : Natural }, damageType : Text, kind : Text }
let Procedure : Type = { ability : Optional Text, attackAbility : Optional Text, attackBonus : Optional { kind : Text, value : Integer }, attackType : Optional Text, description : Optional Text, components : Optional { m : Bool, s : Bool, v : Bool }, dispatches : Optional (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups : Optional (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind : Text, name : Text, onHit : Optional (List Effect), rangeFeet : Optional { long : Natural, normal : Natural }, reachFeet : Optional Natural }
let defaultProcedure : Procedure = { ability = None Text, attackAbility = None Text, attackBonus = None { kind : Text, value : Integer }, attackType = None Text, description = None Text, components = None { m : Bool, s : Bool, v : Bool }, dispatches = None (List { count : { kind : Text, value : Integer }, procedureOrdinal : Natural }), groups = None (List { kind : Text, resourceRefs : { kind : Text, ordinals : List Natural }, spells : List { restriction : Text, spellId : Text } }), kind = "", name = "", onHit = None (List Effect), rangeFeet = None { long : Natural, normal : Natural }, reachFeet = None Natural }
let Action : Type = { description : Optional Text, kind : Text, name : Optional Text, procedure : Optional Procedure, procedureOrdinal : Natural, reason : Optional Text, resourceRefs : { kind : Text, ordinals : Optional (List Natural) } }
let defaultAction : Action = { description = None Text, kind = "", name = None Text, procedure = None Procedure, procedureOrdinal = 0, reason = None Text, resourceRefs = { kind = "none", ordinals = None (List Natural) } }
let defaultEffect : Effect = { amount = { expr = None { dice : Natural, dieSize : Natural, flat : Optional Integer }, kind = "fixed", static = 1 }, damageType = "bludgeoning", kind = "damage" }
in { challengeRating = 2, id = "stat_block_giant_constrictor_snake", kind = "statBlock", name = "Giant Constrictor Snake", provenance = { kind = "srd-5.2.1", section = "Animals.md:772-796" }, statBlock = { abilityScores = { cha = 3, con = 12, dex = 14, int = 1, str = 19, wis = 10 }, ac = { value = { kind = "literal", value = 12 } }, actions = [ defaultAction // { description = Some "The snake makes one Bite attack and uses Constrict.", kind = "textOnly", name = Some "Multiattack", procedureOrdinal = 1, reason = Some "unsupported_procedure_family" }, defaultAction // { description = None Text, kind = "executable", name = None Text, procedure = Some (defaultProcedure // { description = Some "*Melee Attack Roll:* +6, reach 10 ft. *Hit:* 11 (2d6 + 4) Piercing damage.", attackAbility = Some "str", attackBonus = Some { kind = "literal", value = +6 }, attackType = Some "melee", kind = "attack_roll", name = "Bite", onHit = Some [ defaultEffect // { amount = { expr = Some { dice = 2, dieSize = 6, flat = Some +4 }, kind = "fixed", static = 11 }, damageType = "piercing" } ], reachFeet = Some 10 } ), procedureOrdinal = 2 }, defaultAction // { description = Some "*Strength Saving Throw:* DC 14, one Large or smaller creature the snake can see within 10 feet. *Failure:* 13 (2d8 + 4) Bludgeoning damage, and the target has the Grappled condition (escape DC 14).", kind = "textOnly", name = Some "Constrict", procedureOrdinal = 3, reason = Some "unsupported_procedure_family" } ], alignment = "unaligned", communication = { kind = "none" }, creatureType = "beast", hp = { kind = "literal", value = 60 }, initiative = { modifier = +2, score = 12 }, passivePerception = 12, savingThrowModifiers = [ { ability = "str", modifier = +4 }, { ability = "dex", modifier = +2 }, { ability = "con", modifier = +1 }, { ability = "int", modifier = -5 }, { ability = "wis", modifier = +0 }, { ability = "cha", modifier = -4 } ], senses = [ { kind = "blindsight", rangeFeet = 10 } ], size = "huge", skillModifiers = [ { modifier = +2, skill = "perception" } ], speeds = [ { feet = { kind = "literal", value = 30 }, kind = "walk" }, { feet = { kind = "literal", value = 30 }, kind = "swim" } ] } }





