import { defineChatGptBattleTool } from "./battle-execution-tools.ts";

export const CHATGPT_BATTLE_EXECUTION_TOOLS = {
  attack: defineChatGptBattleTool("attack"),
  begin_flurry: defineChatGptBattleTool("begin_flurry"),
  compelled_drop: defineChatGptBattleTool("compelled_drop"),
  compelled_grovel: defineChatGptBattleTool("compelled_grovel"),
  dash: defineChatGptBattleTool("dash"),
  decline_reaction: defineChatGptBattleTool("decline_reaction"),
  disengage: defineChatGptBattleTool("disengage"),
  disperse_spell_area: defineChatGptBattleTool("disperse_spell_area"),
  dodge: defineChatGptBattleTool("dodge"),
  end_turn: defineChatGptBattleTool("end_turn"),
  escape_grapple: defineChatGptBattleTool("escape_grapple"),
  escape_spell_restraint: defineChatGptBattleTool("escape_spell_restraint"),
  focus_dash_and_disengage: defineChatGptBattleTool("focus_dash_and_disengage"),
  focus_disengage_and_dodge: defineChatGptBattleTool(
    "focus_disengage_and_dodge",
  ),
  grapple: defineChatGptBattleTool("grapple"),
  help_attack: defineChatGptBattleTool("help_attack"),
  hide: defineChatGptBattleTool("hide"),
  move: defineChatGptBattleTool("move"),
  multiattack: defineChatGptBattleTool("multiattack"),
  ready_action: defineChatGptBattleTool("ready_action"),
  reduce_ability_check: defineChatGptBattleTool("reduce_ability_check"),
  reduce_attack_damage: defineChatGptBattleTool("reduce_attack_damage"),
  reduce_attack_roll: defineChatGptBattleTool("reduce_attack_roll"),
  reduce_damage_roll: defineChatGptBattleTool("reduce_damage_roll"),
  reduce_fall_damage: defineChatGptBattleTool("reduce_fall_damage"),
  release_grapple: defineChatGptBattleTool("release_grapple"),
  report_area_departure: defineChatGptBattleTool("report_area_departure"),
  report_area_removal: defineChatGptBattleTool("report_area_removal"),
  report_condition_attempt: defineChatGptBattleTool("report_condition_attempt"),
  report_creature_fall: defineChatGptBattleTool("report_creature_fall"),
  report_linked_defense_separation: defineChatGptBattleTool(
    "report_linked_defense_separation",
  ),
  report_possession_attempt: defineChatGptBattleTool(
    "report_possession_attempt",
  ),
  report_ready_trigger: defineChatGptBattleTool("report_ready_trigger"),
  search: defineChatGptBattleTool("search"),
  shake_awake: defineChatGptBattleTool("shake_awake"),
  shove: defineChatGptBattleTool("shove"),
  stand_up: defineChatGptBattleTool("stand_up"),
  adjust_spell_altitude: defineChatGptBattleTool("adjust_spell_altitude"),
  allocate_ongoing_spell_damage: defineChatGptBattleTool(
    "allocate_ongoing_spell_damage",
  ),
  apply_area_damage_and_healing: defineChatGptBattleTool(
    "apply_area_damage_and_healing",
  ),
  apply_feature_condition: defineChatGptBattleTool("apply_feature_condition"),
  assume_beast_form: defineChatGptBattleTool("assume_beast_form"),
  cast_spell: defineChatGptBattleTool("cast_spell"),
  cast_spell_through_companion: defineChatGptBattleTool(
    "cast_spell_through_companion",
  ),
  change_transformation: defineChatGptBattleTool("change_transformation"),
  dismiss_companion: defineChatGptBattleTool("dismiss_companion"),
  dismiss_weapon_imbuement: defineChatGptBattleTool("dismiss_weapon_imbuement"),
  end_concentration: defineChatGptBattleTool("end_concentration"),
  end_ongoing_spell: defineChatGptBattleTool("end_ongoing_spell"),
  gain_extra_action: defineChatGptBattleTool("gain_extra_action"),
  grant_inspiration_die: defineChatGptBattleTool("grant_inspiration_die"),
  heal_from_resource_pool: defineChatGptBattleTool("heal_from_resource_pool"),
  heal_self: defineChatGptBattleTool("heal_self"),
  hurl_spell_light: defineChatGptBattleTool("hurl_spell_light"),
  imbue_held_weapon: defineChatGptBattleTool("imbue_held_weapon"),
  move_and_attack_with_spell_proxy: defineChatGptBattleTool(
    "move_and_attack_with_spell_proxy",
  ),
  move_spell_lights: defineChatGptBattleTool("move_spell_lights"),
  move_spell_zone: defineChatGptBattleTool("move_spell_zone"),
  ram_with_spell_zone: defineChatGptBattleTool("ram_with_spell_zone"),
  re_evoke_spell_weapon: defineChatGptBattleTool("re_evoke_spell_weapon"),
  ready_spell: defineChatGptBattleTool("ready_spell"),
  redirect_spell_area: defineChatGptBattleTool("redirect_spell_area"),
  release_readied_spell: defineChatGptBattleTool("release_readied_spell"),
  release_spell_object: defineChatGptBattleTool("release_spell_object"),
  repeat_spell_contact_damage: defineChatGptBattleTool(
    "repeat_spell_contact_damage",
  ),
  replace_attack_with_area_damage: defineChatGptBattleTool(
    "replace_attack_with_area_damage",
  ),
  resolve_spell_save: defineChatGptBattleTool("resolve_spell_save"),
  return_companion: defineChatGptBattleTool("return_companion"),
  revert_beast_form: defineChatGptBattleTool("revert_beast_form"),
  share_companion_senses: defineChatGptBattleTool("share_companion_senses"),
  steady_aim: defineChatGptBattleTool("steady_aim"),
  sustain_ongoing_feature: defineChatGptBattleTool("sustain_ongoing_feature"),
  temporarily_dismiss_companion: defineChatGptBattleTool(
    "temporarily_dismiss_companion",
  ),
  transfer_spell_mark: defineChatGptBattleTool("transfer_spell_mark"),
  use_granted_area_damage_action: defineChatGptBattleTool(
    "use_granted_area_damage_action",
  ),
} as const;
