import {
  tool,
  refine,
  refineOperations,
  type ChatGptExposureAccounting,
} from "./operation-exposure.ts";

export const BATTLE_SUBJECT_EXPOSURE = {
  "action.attack": tool("attack"),
  "action.dash": tool("dash"),
  "action.disengage": tool("disengage"),
  "action.dodge": tool("dodge"),
  "action.escapeGrapple": tool("escape_grapple"),
  "action.escapeSpellRestraint": tool("escape_spell_restraint"),
  "action.grapple": tool("grapple"),
  "action.helpAttack": tool("help_attack"),
  "action.hide": tool("hide"),
  "action.multiattack": tool("multiattack"),
  "action.ready": tool("ready_action"),
  "action.search": tool("search"),
  "action.shakeAwakeFromAreaControl": tool("shake_awake"),
  "action.shakeAwakeFromStagedCondition": tool("shake_awake"),
  "action.shove": tool("shove"),
  "actionSpell.cast": refine("spellOperations"),
  "actionSpell.ready": tool("ready_spell"),
  "bonusAction.martialArtsUnarmedStrike": tool("attack"),
  "bonusAction.offHandAttack": tool("attack"),
  "bonusAction.statBlockActionOption": refine("statBlockBonusActions"),
  "bonusActionDashSpell.cast": tool("cast_spell"),
  "bonusActionSpell.cast": refine("spellOperations"),
  "bonusActionStandardAction.dash": tool("dash"),
  "bonusActionStandardAction.disengage": tool("disengage"),
  "bonusActionStandardAction.hide": tool("hide"),
  companionAttack: tool("attack"),
  "companionLifecycle.permanentlyDismiss": tool("dismiss_companion"),
  "companionLifecycle.reappear": tool("return_companion"),
  "companionLifecycle.temporarilyDismiss": tool(
    "temporarily_dismiss_companion",
  ),
  "druidWildShape.assumeForm": tool("assume_beast_form"),
  "druidWildShape.dismiss": tool("revert_beast_form"),
  monkFocusFlurryOfBlowsStrike: tool("attack"),
  "monkFocusOption.flurryOfBlows": tool("begin_flurry"),
  "monkFocusOption.patientDefense.focusDisengageDodge": tool(
    "focus_disengage_and_dodge",
  ),
  "monkFocusOption.patientDefense.freeDisengage": tool("disengage"),
  "monkFocusOption.stepOfTheWind.focusDisengageDash": tool(
    "focus_dash_and_disengage",
  ),
  "monkFocusOption.stepOfTheWind.freeDash": tool("dash"),
  "runtimeCommand.castAttackHitBonusActionSpell": tool("cast_spell"),
  "runtimeCommand.startSpellCasting": tool("cast_spell"),
  "runtimeCommand.continueSpellCasting": tool("cast_spell"),
  "runtimeCommand.castTriggeredReactionSpell": tool("cast_spell"),
  "runtimeCommand.controlledVerticalSuspensionAltitudeControl": tool(
    "adjust_spell_altitude",
  ),
  "runtimeCommand.creatureFalls": tool("report_creature_fall"),
  "runtimeCommand.creatureTypeProtectionConditionAttempt": tool(
    "report_condition_attempt",
  ),
  "runtimeCommand.creatureTypeProtectionPossessionAttempt": tool(
    "report_possession_attempt",
  ),
  "runtimeCommand.directionalPersistentAreaDirectionChange": tool(
    "redirect_spell_area",
  ),
  "runtimeCommand.directionalPersistentAreaSave": tool("resolve_spell_save"),
  "runtimeCommand.endConcentration": tool("end_concentration"),
  "runtimeCommand.endPersistentAreaSaveConditionEscapeForAreaRemoval": tool(
    "report_area_removal",
  ),
  "runtimeCommand.endPersistentAreaSaveConditionEscapeForDeparture": tool(
    "report_area_departure",
  ),
  "runtimeCommand.endPersistentAreaSaveDamageForEnvironment": tool(
    "disperse_spell_area",
  ),
  "runtimeCommand.endPersistentAreaTraitForEnvironment": tool(
    "disperse_spell_area",
  ),
  "runtimeCommand.endTurn": tool("end_turn"),
  "runtimeCommand.executeCompelledApproach": tool("move"),
  "runtimeCommand.executeCompelledDrop": tool("compelled_drop"),
  "runtimeCommand.executeCompelledFlee": tool("move"),
  "runtimeCommand.executeCompelledGrovel": tool("compelled_grovel"),
  "runtimeCommand.fixedCostMovementReplacement": tool("move"),
  "runtimeCommand.grantedAreaSaveDamageAction": tool(
    "use_granted_area_damage_action",
  ),
  "runtimeCommand.linkedDefenseResistanceDamageShareSeparation": tool(
    "report_linked_defense_separation",
  ),
  "runtimeCommand.movableZoneRam": tool("ram_with_spell_zone"),
  "runtimeCommand.movableZoneReposition": tool("move_spell_zone"),
  "runtimeCommand.movableZoneSave": tool("resolve_spell_save"),
  "runtimeCommand.move": tool("move"),
  "runtimeCommand.opportunityAttack": tool("attack"),
  "runtimeCommand.persistentAreaSaveCompositeSave": tool("resolve_spell_save"),
  "runtimeCommand.persistentAreaSaveConditionEscapeSave":
    tool("resolve_spell_save"),
  "runtimeCommand.persistentAreaSaveConditionSave": tool("resolve_spell_save"),
  "runtimeCommand.persistentAreaSaveDamageExit": tool("report_area_departure"),
  "runtimeCommand.persistentAreaSaveDamageSave": tool("resolve_spell_save"),
  "runtimeCommand.protectionRelevantEffectSave": tool("resolve_spell_save"),
  "runtimeCommand.releaseGrapple": tool("release_grapple"),
  "runtimeCommand.releaseReadiedAction": refine("readiedActionSubjects"),
  "runtimeCommand.releaseReadiedAttack": tool("attack"),
  "runtimeCommand.releaseReadiedMovement": tool("move"),
  "runtimeCommand.releaseReadiedSpell": tool("release_readied_spell"),
  "runtimeCommand.releaseSpellCreatedHeldObject": tool("release_spell_object"),
  "runtimeCommand.replaceSelfTransformationMode.aquaticAdaptation": tool(
    "change_transformation",
  ),
  "runtimeCommand.replaceSelfTransformationMode.changeAppearance": tool(
    "change_transformation",
  ),
  "runtimeCommand.replaceSelfTransformationMode.naturalWeapons": tool(
    "change_transformation",
  ),
  "runtimeCommand.reportReadyTrigger": tool("report_ready_trigger"),
  "runtimeCommand.retaliationAttack": tool("attack"),
  "runtimeCommand.standFromProne": tool("stand_up"),
  spawnedCompanionSharedSenses: tool("share_companion_senses"),
  "spawnedCompanionTouchSpellProxy.cast": tool("cast_spell_through_companion"),
  unitFeature: refineOperations(
    "procedureBindings",
    "unitFeature",
    "unitSupportProfile",
  ),
  unitFeatureHeldWeaponActivation: tool("imbue_held_weapon"),
} as const satisfies ChatGptExposureAccounting["battleSubjects"];
