export {
  BattleCombatantSide,
  BattleId,
  BattleReplayStackDepth,
  CombatantId,
  battleCombatantSide,
  battleId,
  battleReplayStackDepth,
  characterId,
  combatantId,
  initiativeScore,
  type CharacterId,
  type InitiativeScore,
} from "./identity.ts";
export type {
  CharacterZeroHpLifecycleInit,
  ZeroHpLifecycle,
} from "./zero-hp-lifecycle.ts";
export type {
  CharacterBattleClassLevel,
  CharacterBattleClassLevelInit,
} from "./character-class-level.ts";
export {
  characterBattleResourceUsage,
  type CharacterBattleFeatureInit,
  type CharacterBattleResourceInit,
  type CharacterBattleResourceState,
  type CharacterBattleSpellSlotInit,
  type CharacterBattleSpellSlotExpenditureInit,
  type CharacterBattleSpellSlotState,
  type CharacterBattleSpellcastingInit,
  type CharacterBattleSpellcastingState,
} from "./character-battle-resources.ts";
export {
  BATTLE_REACTION_TRIGGERS,
  BATTLE_READIED_SPELL_TRIGGERS,
  type BattleReactionTrigger,
  type BattleReadiedSpellTrigger,
} from "./battle-reaction-triggers.ts";
export {
  BATTLE_RUNTIME_COMMANDS,
  BATTLE_MOVEMENT_SPEED_KINDS,
  BATTLE_SUBJECT_ACTIONS,
  BATTLE_SUBJECT_BONUS_ACTIONS,
  BattleSubjectSchema,
  sameBattleSubject,
  type BattleRuntimeCommand,
  type BattleMovementSpeedKind,
  type BattleSubject,
  type BattleSubjectAction,
  type BattleSubjectBonusAction,
} from "./battle-subjects.ts";
export type {
  BattleWeaponDamage,
  CharacterAttackActionOption,
  CharacterUnarmedStrikeActionOption,
  CharacterWeaponAttackActionOption,
  StatBlockAttackActionOption,
  StatBlockDailyUseState,
  StatBlockLegendaryActionResourceSnapshot,
  StatBlockLimitedUseSnapshot,
  StatBlockMutableResourceState,
  StatBlockPartKey,
  StatBlockPartSection,
  StatBlockResourceSnapshot,
  SupportedAttackActionOption,
  SupportedCreatureNamedAttackRoll,
  UnarmedStrikeDamageEffect,
  UnarmedStrikeDamageProfile,
} from "./battle-action-options.ts";
export type {
  BattleCreatureInit,
  BattlePositiveHpUnconscious,
  BattleUnitRef,
  BattleWalkSpeed,
  CharacterBattleCreatureInit,
  CharacterBattleLoadoutRef,
  StatBlockBattleCreatureInit,
  StatBlockBattleInitInput,
} from "./battle-init.ts";
export { KNOCKED_OUT_UNCONSCIOUS } from "./battle-init.ts";
export {
  ActiveOngoingFeatureOccurrenceSnapshotSchema,
  BATTLE_INVALID_REASON_CODES,
  BattleFillSchema,
  BattleHoleSchema,
  BattleSnapshotSchema,
  addBattleCombatant,
  battleCreatureInitFromStatBlock,
  breakBattleConcentration,
  combatantKnockedOutUnconscious,
  concentrationSavingThrowDc,
  discoverBattleActs,
  endTurn,
  openBattleReactionWindow,
  removeBattleCombatants,
  resolveBattleConcentrationDamage,
  resolveBattleReaction,
  resolveBattleSubject,
  scoreModifier,
  snapshotBattle,
  startBattle,
  type ActiveOngoingFeatureOccurrence,
  type ActiveOngoingFeatureOccurrenceSnapshot,
  type ActiveOngoingFeatureOccurrenceSnapshotEncoded,
  type BattleAttackDamageDisposition,
  type AttackDamageRider,
  type AttackDamageRiderUsage,
  type AttackRollFeatureActivation,
  type AvailableBattleAct,
  type BattleAbilityCheckHole,
  type BattleActiveEffect,
  type BattleActiveEffectExpiration,
  type BattleAttackRollHole,
  type BattleAttackRollResult,
  type BattleConcentration,
  type BattleConcentrationSavingThrowHole,
  type BattleCreatureSnapshot,
  type BattleCreatureState,
  type BattleCreatureZeroHpLifecycleSnapshot,
  type BattleDamageRollHole,
  type BattleDeathSavingThrowHole,
  type BattleFill,
  type BattleGrappleLink,
  type BattleGrappleOutcomeHole,
  type BattleHand,
  type BattleHelpAttack,
  type BattleHiddenState,
  type BattleHidePrerequisite,
  type BattleHole,
  type BattleHoleId,
  type BattleHoleInstanceKey,
  type BattleInterruptedProcedure,
  type BattleInvalidReasonCode,
  type BattleMovementFillValue,
  type BattleMovementHole,
  type BattleReactionDecision,
  type BattleReactionDecisionHole,
  type BattleReactionFrame,
  type BattleReactionProcedureChoice,
  type BattleReactionProcedureSelection,
  type BattleReadiedMovement,
  type BattleReadiedSpell,
  type BattleResolutionInput,
  type BattleResolutionResult,
  type BattleRolledDiceFill,
  type BattleSavingThrowOutcome,
  type BattleSavingThrowRollModeProjection,
  type BattleSnapshot,
  type BattleSpellAreaChoice,
  type BattleSpellAttackRollHole,
  type BattleSpellDamageRollHole,
  type BattleSpellHealingRollHole,
  type BattleSpellEffectEarlyEnd,
  type BattleSpellSavingThrowOutcomeHole,
  type BattleStatBlockRechargeRollHole,
  type BattleStatBlockRechargeRollResult,
  type BattleState,
  type BattleStateInitIssue,
  type BattleTargetChoiceHole,
  type BattleTurnResources,
  type BattleUnitFeatureRollHole,
  type LegendaryActionWindow,
  type OngoingFeatureExpiration,
  type OngoingFeatureSource,
  type OngoingFeatureSourceKey,
  type SupportedSpellAct,
} from "./battle-reducer.ts";
export {
  ATTACK_DAMAGE_RIDER_SUPPORT_PROFILE,
  ATTACK_ACTION_ATTACK_COUNT_SCALING_SUPPORT_PROFILE,
  BATTLE_UNIT_SUPPORT_PROFILES,
  PASSIVE_ARMOR_CLASS_BONUS_SUPPORT_PROFILE,
  PASSIVE_RANGED_ATTACK_ROLL_BONUS_SUPPORT_PROFILE,
  PASSIVE_SPEED_BONUS_SUPPORT_PROFILE,
  REACTION_ROLL_OR_DAMAGE_REDUCTION_SUPPORT_PROFILE,
  SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  WEAPON_DAMAGE_DICE_ROLL_CHOICE_SUPPORT_PROFILE,
  WEAPON_OR_UNARMED_CRITICAL_RANGE_19_SUPPORT_PROFILE,
  battleAttackDamageRiderSupportForUnit,
  battleAttackActionAttackCountScalingSupportForUnit,
  battleBonusActionStandardActionSupportForUnit,
  battlePassiveArmorClassBonusSupportForUnit,
  battlePassiveRangedAttackRollBonusSupportForUnit,
  battlePassiveSpeedBonusSupportForUnit,
  battleReactionRollOrDamageReductionSupportForUnit,
  battleSaveDamageReplacementSupportForUnit,
  battleUnitRefWithSupportProfiles,
  battleUnitSupportProfilesForUnit,
  battleWeaponDamageDiceRollChoiceSupportForUnit,
  battleWeaponOrUnarmedCriticalRange19SupportForUnit,
  attackActionAttackCountScalingProfileForUnit,
  passiveArmorClassBonusProfileForUnit,
  passiveRangedAttackRollBonusProfileForUnit,
  passiveSpeedBonusProfileForUnit,
  type BattleAttackDamageRiderSupport,
  type BattleAttackActionAttackCountScalingSupport,
  type BattleBonusActionStandardActionSupport,
  type BattlePassiveArmorClassBonusSupport,
  type BattlePassiveRangedAttackRollBonusSupport,
  type BattlePassiveSpeedBonusSupport,
  type BattleReactionRollOrDamageReductionSupport,
  type BattleSaveDamageReplacementSupport,
  type BattleUnitSupportProfile,
  type BattleUnitSupportProfileIssue,
  type BattleWeaponOrUnarmedCriticalRange19Support,
  type BattleWeaponDamageDiceRollChoiceSupport,
  type PassiveArmorClassBonusProfile,
  type PassiveRangedAttackRollBonusProfile,
  type PassiveSpeedBonusProfile,
  type WeaponDamageDiceRollChoiceProfile,
} from "./unit-feature-support.ts";
