export {
  BattleAttackExecutionScopeRef,
  BattleAttackProcedureExecutionRef,
  BattleCharacterExecutionScopeRef,
  BattleDancingLightId,
  BattleId,
  BattleLineDirectionId,
  BattleObjectId,
  BattleProcedureExecutionRef,
  BattleStatBlockProcedureExecutionRef,
  BattleReplayStackDepth,
  BattleResourcePoolExecutionRef,
  BattleTablePositionId,
  CombatantId,
  SpellId,
  battleAttackExecutionScopeRef,
  battleAttackProcedureExecutionRef,
  battleAreaId,
  battleCharacterExecutionScopeRef,
  battleExecutionScopeOrdinal,
  battleProcedureExecutionRef,
  battleStatBlockExecutionScopeRef,
  battleResourcePoolExecutionRef,
  battleDancingLightId,
  battleId,
  battleLineDirectionId,
  battleObjectId,
  battleReplayStackDepth,
  battleSpellEffectOccurrenceId,
  battleTablePositionId,
  characterId,
  combatantId,
  initiativeScore,
  spellId,
  type BattleAreaId,
  type BattleSpellEffectOccurrenceId,
  type CharacterId,
  type InitiativeScore,
} from "./identity.ts";

export type {
  CharacterExecutionAdmission,
  CharacterExecutionState,
  CharacterProcedureBinding,
  CharacterUnitProcedureOwnership,
} from "./character-execution-admission.ts";

export {
  emptyBattleRuntimeContext,
  type BattleRuntimeContext,
  type BattleRuntimeSession,
  type CharacterBattleRuntimeContext,
  type CharacterSpellPresentationSource,
  type RetainedCompanionBattleSelection,
} from "./battle-runtime-context.ts";

export {
  characterProcedureBinding,
  characterProcedureBindingSnapshots,
} from "./character-execution-admission.ts";

export type {
  StatBlockExecutionAdmission,
  StatBlockExecutionRestoreIssue,
  StatBlockExecutionRestoration,
  StatBlockExecutionSnapshot,
  StatBlockExecutionState,
  StatBlockProcedureBinding,
  StatBlockProcedureBindingSnapshot,
  StatBlockResourcePoolState,
} from "./stat-block-execution.ts";

export {
  restoreStatBlockExecutionAdmission,
  restoreStatBlockExecutionAdmissions,
  statBlockExecutionSnapshot,
} from "./stat-block-execution.ts";

export type {
  CharacterZeroHpLifecycleInit,
  ZeroHpLifecycle,
} from "./zero-hp-lifecycle.ts";

export {
  BATTLE_TRACE_HOLE_KINDS,
  battleActTraceCheckpoint,
  battleResolutionTraceCheckpoint,
  battleTraceHoleKinds,
  type BattleTraceCheckpoint,
  type BattleTraceHoleKind,
} from "./battle-trace-contract.ts";

export { objectInvisibleBenefitDenied } from "./battle-reducer/attack-roll.ts";

export {
  BattleActPresentationSchema,
  BattleInterruptProcedureChoiceSchema,
  BattleSpellPresentationSchema,
  BattleUnitSupportSourceSchema,
} from "./battle-reducer/battle-codecs.ts";

export {
  spellActiveEffectExecutionRef,
  spellActiveEffectForExecutionRef,
} from "./active-effect/execution-ref.ts";

export {
  battleActSpellPresentation,
  battleActDruidWildShapePresentation,
  battleActSpellSlotPresentation,
  battleActUnitPresentation,
  battleAdmittedSpellPresentations,
  battleSelectedSpellInvocationForProcedure,
  battleSubjectPresentation,
  discoverBattleActs,
} from "./battle-act-composition.ts";

export {
  combatantCanSee,
  combatantHasSeeInvisibleAndEtherealEffect,
  seeInvisibleRevealsEtherealWitness,
  seeInvisibleRevealsInvisibleObject,
} from "./battle-reducer/creature-state-leaves.ts";

export {
  battleWeaponItemHasMagicWeaponEnhancement,
  battleWeaponItemMagicWeaponEnhancementBonus,
} from "./battle-reducer/attack-damage-apply.ts";

export {
  battleHoleFamilyKind,
  thaumaturgyBoomingVoiceInfluenceAbilityCheckHole,
  type BattleHoleFamilyKind,
} from "./battle-reducer/hole-helpers.ts";

export {
  battleFillKind,
  battleSubjectKind,
  type BattleFillKind,
  type BattleSubjectKind,
} from "./battle-protocol-kinds.ts";

export type {
  CharacterBattleClassLevel,
  CharacterBattleClassLevelInit,
  CharacterBattleClassLevelInits,
  CharacterBattleClassLevels,
} from "./character-class-level.ts";

export {
  CHARACTER_BATTLE_METAMAGIC_EFFECT_KINDS,
  PACT_OF_THE_CHAIN_FIND_FAMILIAR_INVOCATION_MODE,
  characterBattleResourceSupportedForUnit,
  admitCharacterBattleResources,
  characterBattleResourceUsage,
  characterBattleResourceForUnit,
  characterBattleResourceMaxUses,
  characterBattleResourceMaxPoints,
  characterBattleResourceIsPointPool,
  characterBattleResourceIsUseCount,
  classFeatureSpellFreeCastProfileForResource,
  parseCharacterBattleClassLevels,
  characterResourceIsFavoredEnemyFreeCast,
  characterResourceIsClassFeatureFreeCastForSpell,
  effectiveCharacterBattleCantrips,
  effectiveCharacterBattlePreparedSpells,
  spendCharacterPointPoolResource,
  unitIsFavoredEnemyHuntersMarkFreeCastResource,
  unitIsSupportedClassFeatureSpellFreeCastResource,
  type CharacterBattleBookOfShadowsSpellAccessInit,
  type CharacterBattleClassLevelsIssue,
  type CharacterBattleBookOfShadowsPresence,
  type CharacterBattleFeaturePreparedSpellInit,
  type CharacterBattleFeatureInit,
  type CharacterBattleInvocationSpellAccessInit,
  type CharacterBattleInvocationSpellAccessState,
  type CharacterBattleMetamagicEffectKind,
  type CharacterBattleMetamagicInit,
  type CharacterBattleMetamagicOptionFact,
  type CharacterBattleMetamagicState,
  type CharacterBattlePointPoolResourceState,
  type CharacterBattlePointPoolSpendIssue,
  type CharacterBattleResourceInit,
  type CharacterBattleResourceAdmission,
  type CharacterBattleResourceExecutionFacts,
  type CharacterBattleResourceOwnership,
  type CharacterBattleResourceState,
  type CharacterBattleUseCountResourceState,
  type CharacterBattleSpellSlotInit,
  type CharacterBattleSpellSlotExpenditureInit,
  type CharacterBattleSpellSlotState,
  type CharacterBattleSpellbookRitualSpellAccessInit,
  type CharacterBattleSpellcastingInit,
  type CharacterBattleSpellcastingExecutionState,
  type CharacterBattleSpellcastingState,
  type PactOfTheChainFindFamiliarInvocationMode,
} from "./character-battle-resources.ts";

export {
  admitCompanionToBattle,
  applyFindFamiliarZeroHitPointDisappearance,
  castFindFamiliar,
  castWildCompanion,
  permanentlyDismissFindFamiliar,
  reappearTemporarilyDismissedFindFamiliar,
  retainedStoredFormForPresentCompanion,
  temporarilyDismissFindFamiliar,
  type CompanionBattleAdmissionInput,
  type CompanionBattleEmbodiedAdmissionManifestation,
  type CompanionBattleAdmissionFormEligibility,
  type CompanionBattleAdmissionManifestation,
  type CompanionBattleStoredAdmissionManifestation,
  type FindFamiliarCastInput,
  type FindFamiliarLifecycleInputBase,
  type FindFamiliarReappearanceInput,
  type WildCompanionCastInput,
  type WildCompanionSpend,
} from "./find-familiar-lifecycle.ts";
export {
  admitCompanionToBattleRuntime,
  castRetainedFindFamiliarRuntime,
  type RetainedCompanionRuntimeCastResult,
} from "./find-familiar-presentation.ts";

export type {
  BattleCompanionAbsentState,
  BattleCompanionPlacement,
  BattleCompanionDurableId,
  BattleCompanionIdentity,
  BattleCompanionPresentState,
  BattleCompanionSnapshot,
  BattleCompanionState,
  BattleCompanionStoredForm,
} from "./companion-state.ts";

export {
  findFamiliarCompanionEntryForOwner,
  findFamiliarCompanionForOwner,
  findFamiliarCreatureTypeOverrideForOwner,
} from "./find-familiar-state.ts";

export {
  FIND_FAMILIAR_TELEPATHY_RANGE_FEET,
  findFamiliarTelepathicConnection,
  type FindFamiliarSharedSensesEffect,
  type FindFamiliarTelepathicConnection,
  type FindFamiliarWithin100FeetFact,
} from "./find-familiar-telepathy.ts";

export {
  deliverTouchSpellThroughFindFamiliar,
  shareFindFamiliarSenses,
} from "./battle-execution-composition.ts";

export type { PactOfTheChainFamiliarAttackSubject } from "./find-familiar-pact-chain.ts";

export {
  battleCreaturePresentationDisplayName,
  statBlockProcedurePresentations,
} from "./stat-block-presentation.ts";

export {
  combatantPerceptionCommunicationProjection,
  type BattleCharacterSpeechProjection,
  type BattleCreatureCommunicationProjection,
  type BattleCreaturePerceptionCommunicationProjection,
  type BattleCreatureSpecialSense,
  type BattleStatBlockCommunicationText,
} from "./creature-perception-communication.ts";

export {
  BATTLE_INTERRUPT_TRIGGERS,
  BATTLE_READIED_SPELL_TRIGGERS,
  type BattleInterruptTrigger,
  type BattleReadiedSpellTrigger,
} from "./battle-interrupt-triggers.ts";

export {
  BATTLE_RUNTIME_COMMANDS,
  BATTLE_MOVEMENT_SPEED_KINDS,
  BATTLE_SUBJECT_ACTIONS,
  BATTLE_SUBJECT_BONUS_ACTIONS,
  CANTRIP_SPELL_PROCEDURES,
  BattleSubjectSchema,
  SPELL_SLOT_PROCEDURES,
  SpellInvocationRefSchema,
  SpellMetamagicSelectionSchema,
  SpellSubjectModeSchema,
  armorOfShadowsSpellInvocationRef,
  cantripSpellInvocationRef,
  classFeatureFreeCastSpellInvocationRef,
  isCharacterProcedureBattleSubject,
  sameBattleSubject,
  spellSlotInvocationRef,
  type BattleRuntimeCommand,
  type BattleMovementSpeedKind,
  type BattleSubject,
  type BattleSubjectAction,
  type BattleSubjectBonusAction,
  type CantripSpellProcedure,
  type SpellInvocationRef,
  type SpellInvocationRefEncoded,
  type SpellMetamagicSelection,
  type SpellSlotProcedure,
  type SpellSubjectMode,
} from "./battle-subjects.ts";

export type {
  BattleWeaponDamage,
  CharacterAttackActionOption,
  CharacterUnarmedStrikeActionOption,
  CharacterWeaponAttackActionOption,
  CharacterWeaponAttackDamageTypeChoices,
  StatBlockAttackActionOption,
  SupportedAttackActionOption,
  UnarmedStrikeDamageEffect,
  UnarmedStrikeDamageProfile,
} from "./battle-action-options.ts";

export type {
  BattleDruidWildShapeKnownForm,
  BattleDruidWildShapeKnownFormIssue,
  BattleCreatureInit,
  BattlePositiveHpUnconscious,
  BattleUnitRef,
  BattleWalkSpeed,
  CharacterBattleCreatureInit,
  CharacterBattleCreatureInitWeaponAttack,
  CharacterBattleD20Statistics,
  CharacterBattleInvocationFeature,
  CharacterBattleLoadoutRef,
  CharacterBattleWeaponMasterySelection,
  StatBlockBattleCreatureInit,
  StatBlockBattleInitInput,
} from "./battle-init.ts";

export {
  KNOCKED_OUT_UNCONSCIOUS,
  battleAvailableDruidWildShapeKnownForms,
  characterBattleCreatureInitWeaponAttack,
} from "./battle-init.ts";

export {
  WILD_SHAPE_FORM_ACTION_SURFACE_CATEGORIES,
  wildShapeFormActionSurfaceInventory,
  type WildShapeFormActionSurfaceCategory,
  type WildShapeFormActionSurfaceInventoryEntry,
} from "./statblock-action-support.ts";

export {
  BATTLE_INVALID_REASON_CODES,
  type ActiveOngoingFeatureOccurrence,
  type ActiveOngoingFeatureOccurrenceSnapshot,
  type ActiveOngoingFeatureOccurrenceSnapshotEncoded,
  type BattleAttackDamageDisposition,
  type AttackDamageRider,
  type AttackDamageRiderUsage,
  type AttackRollFeatureActivation,
  type AvailableBattleAct,
  type BattleActPresentation,
  type BattleAbilityCheckHole,
  type BattleActiveEffect,
  type BattleActiveEffectExpiration,
  type BattleAcrobaticMovementFact,
  type BattleAcrobaticMovementPath,
  type BattleAttackRollHole,
  type BattleAttackRollResult,
  type BattleBardicInspirationFailedD20TestFacts,
  type BattleConcentration,
  type BattleConcentrationSavingThrowHole,
  type BattleCreatureSnapshot,
  type BattleCreatureState,
  type BattleCreatureZeroHpLifecycleSnapshot,
  type CharacterBattleCreatureState,
  type BattleDamageRollHole,
  type BattleDeathSavingThrowHole,
  type BattleDamageRelationshipDecision,
  type BattleDamageRelationshipDecisionFill,
  type BattleDamageRelationshipDecisions,
  type BattleFailedAbilityCheckFacts,
  type BattleFallDamageLandingResult,
  type BattleFeatherFallLandingResult,
  type BattleFill,
  type BattleGrappleLink,
  type BattleGrappleOutcomeHole,
  type BattleHand,
  type BattleHelpAttack,
  type BattleHiddenState,
  type BattleHidePrerequisite,
  type BattleHitPointHealingPoolAllocation,
  type BattleHitPointHealingPoolDistributionHole,
  type BattleHole,
  type BattleHoleId,
  type BattleHoleInstanceKey,
  type BattleFlySpeedGrantEndFallCleanupFrame,
  type BattleInterruptFrame,
  type BattleInterruptedProcedure,
  type BattleInvalidReasonCode,
  type BattleIllumination,
  type BattleLightEmission,
  type BattleSeeInvisibleEtherealWitness,
  type BattleSeeInvisibleObjectWitness,
  type BattleLightEmitter,
  type BattleLightEmitterAttachment,
  type BattleLightEmitterProjection,
  type BattleLightEmitterProjectionFact,
  type BattleLightlyObscuredPerceptionRollMode,
  type BattleMagicalDarknessNonmagicalLightProjectionFact,
  type BattleMagicalDarknessSightProjectionFact,
  type BattleMagicalDarknessZone,
  type BattleMagicWeaponTargetItemFact,
  type BattleMagicWeaponTargetItemHole,
  type BattleAntimagicFieldAffectedOngoingSpellEffect,
  type BattleAntimagicFieldOngoingSpellEffectRef,
  type BattleObscurementZone,
  type BattleMovementFillValue,
  type BattleMovementHole,
  type BattleObjectDamageDisposition,
  type BattleObjectDamageOutcome,
  type BattleObjectIgnitionDisposition,
  type BattleObjectIgnitionOutcome,
  type BattleObjectOutline,
  type BattleObjectTargetChoiceHole,
  type BattleAntimagicFieldAuraMembership,
  type BattleAntimagicFieldTransitWitness,
  type BattlePossessionAttemptDisposition,
  type BattleInterruptDecision,
  type BattleInterruptDecisionHole,
  type BattleInterruptCheckpoint,
  type BattleInterruptProcedureChoice,
  type BattleInterruptProcedureSelection,
  type BattleReadiedMovement,
  type BattleReadiedSpell,
  type AdmittedBattleResolutionInput,
  type BattleResolutionCandidateInput,
  type BattleResolutionInput,
  type BattleResolutionResult,
  type BattleRolledDiceFill,
  type BattleSavingThrowOutcome,
  type BattleSavingThrowRollModeProjection,
  type BattleSightObserver,
  type BattleSightObscurement,
  type BattleSnapshot,
  type BattlePresentedCreatureSnapshot,
  type BattlePresentedSnapshot,
  type BattleSnapshotPresentationIssue,
  type BattleSnapshotPresentationIssues,
  type BattleStoredLightEmitter,
  type BattleSpellAreaChoice,
  type BattleSpellAreaOriginAnchor,
  type BattleSpellAttackRollHole,
  type BattleSpellConditionChoiceHole,
  type BattleSpellConditionEndTurnSavingThrowOutcomeHole,
  type BattleSpellDamageRollHole,
  type BattleSpellDamageTypeChoiceHole,
  type BattleSpellHealingRollHole,
  type BattleSpellEffectEarlyEnd,
  type BattleSpellSavingThrowOutcomeHole,
  type BattleSelfTransformationModeChoiceHole,
  type BattleStatBlockRechargeRollHole,
  type BattleStatBlockRechargeRollResult,
  type BattleState,
  type BattleStateInitIssue,
  type BattleStateInitLeafIssue,
  type BattleSuccessfulAbilityCheckFacts,
  type BattleTargetChoiceHole,
  type BattleTargetSpatialFact,
  type BattleAttackExecutionSelection,
  type BattleSelectedSpellInvocation,
  type BattleThaumaturgyActiveOneMinuteEffectCountHole,
  type BattleTrackedOngoingSpellLightEmitter,
  type BattleTurnResources,
  type BattleUnitFeatureRollHole,
  type BattleWildShapeEquipmentDispositionHole,
  type EndedFlySpeedGrant,
  type BardicInspirationFailedD20TestResolutionInput,
  type BardicInspirationFailedD20TestResolutionResult,
  type FailedAbilityCheckResourceBoostResolutionInput,
  type FailedAbilityCheckResourceBoostResolutionResult,
  type LegendaryActionWindow,
  type OngoingFeatureExpiration,
  type OngoingFeatureSourceKey,
  type SelfTransformationModeSpellInvocation,
  type SupportedSpellInvocation,
  type MagicWeaponEnhancementBonus,
  type MagicWeaponEnhancementSpellInvocation,
  type ThaumaturgyBoomingVoiceSpellInvocation,
  type SuccessfulAbilityCheckReactionReductionResolutionInput,
  type SuccessfulAbilityCheckReactionReductionResolutionResult,
} from "./battle-state-execution.ts";
export {
  ActiveOngoingFeatureOccurrenceSnapshotSchema,
  BattleDroppedObjectOutcomeSchema,
  BattleFillSchema,
  BattleHoleSchema,
  BattleObjectDamageOutcomeSchema,
  BattleObjectIgnitionOutcomeSchema,
  BattleShovePushOutcomeSchema,
  BattleSnapshotSchema,
  BattlePresentedSnapshotSchema,
  StatBlockExecutionSnapshotSchema,
} from "./battle-reducer/battle-codecs.ts";
export {
  BattleCreatureDisplayNameSchema,
  type BattleCreatureDisplayName,
} from "./battle-creature-display-name.ts";
export { battlePresentedSnapshot } from "./battle-snapshot-presentation.ts";
export {
  addBattleRuntimeCombatant,
  applyInitiativeSwap,
  finishInitialInitiativeSetup,
  removeBattleRuntimeCombatants,
  requiredInitiativeRollModeForCombatant,
  startBattle,
  startBattleWithInitialInitiativeSetup,
  type InitialInitiativeSetup,
  type InitiativeSwapCandidateWitness,
} from "./battle-reducer/api-lifecycle.ts";
export {
  activeFeatherFallDescentRateCapFeetPerRound,
  activeSelfTransformationModeEffect,
  battleIlluminationFromLightEmitters,
  battleMagicalDarknessNonmagicalLightIllumination,
  battleMagicalDarknessSightObscurement,
  battleCreatureCanBreatheUnderwater,
  battleLightEmitterProjection,
  battleLightEmitters,
  battleObscurementZones,
  battlePerceptionRollModeForObscurement,
  battlePerceptionRollModeForSight,
  battleSightObscurement,
  FEATHER_FALL_DESCENT_RATE_CAP_FEET_PER_ROUND,
} from "./battle-reducer/spells-active-effects.ts";
export {
  activeFeatureSpellSaveDcRouteEvents,
  battleReducerStartRouteEvent,
  passiveSavingThrowRollModeRouteEvents,
  type BattleReducerRouteEvent,
  type BattleReducerRouteEvents,
  type BattleReducerRouteFill,
  type BattleReducerRouteHole,
  type BattleReducerRouteOwnerGroup,
  type BattleReducerRouteSubjectFamily,
} from "./battle-reducer/reducer-route.ts";
export { battleCreatureInitFromStatBlock } from "./battle-init.ts";
export { spellSaveDcForCaster } from "./battle-reducer/spell-save-dc.ts";
export {
  breakBattleConcentration,
  resolveBattleConcentrationDamage,
} from "./battle-reducer/damage-apply.ts";
export { combatantKnockedOutUnconscious } from "./battle-reducer/creature-state.ts";
export {
  battleStateInitIssueMessage,
  concentrationSavingThrowDc,
  scoreModifier,
} from "./battle-reducer/domain-helpers.ts";
export { discoverBattleActCandidates } from "./battle-execution-composition.ts";
export {
  openBattleInterruptWindow,
  type FlyEndCanStopFallReason,
  type FlySpeedGrantEndFallWitness,
  type FlySpeedGrantEndFallWitnessResult,
} from "./battle-reducer/dispatcher.ts";
export {
  battleSnapshotProjection,
  endTurn,
  openCreatureFallsInterruptWindow,
  resolveBattleInterrupt,
  resolveFallDamageLanding,
  resolveFeatherFallLanding,
  resolveFlySpeedGrantEndFallCleanup,
  snapshotBattle,
} from "./battle-execution-composition.ts";
export {
  resolveFailedAbilityCheckResourceBoost,
  resolveSuccessfulAbilityCheckReactionReduction,
  resolveBardicInspirationFailedD20Test,
} from "./battle-reducer/unit-features.ts";
export {
  SELF_TRANSFORMATION_MODE_KINDS,
  type SelfTransformationModeKind,
} from "./battle-reducer/domain-constants.ts";
export { SPELL_CAST_REACTION_FACTS_HOLE_ID } from "./battle-reducer/battle-runtime-protocol.ts";
export {
  validateWildShapeEquipmentDispositionFill,
  wildShapeLoadoutObjectRefs,
  type ActiveWildShapeEquipmentDisposition,
  type WildShapeEquipmentDispositionChoice,
  type WildShapeEquipmentDispositionFillValue,
  type WildShapeLoadoutObjectRef,
} from "./battle-reducer/wild-shape-equipment.ts";
export {
  type AttackDamageAbilityModifierChoice,
  type AttackDamageAbilityModifierChoiceFill,
  type AttackDamageAbilityModifierChoiceSelection,
  type AttackDamageAbilityModifierChoiceProcedureRefs,
} from "./battle-reducer/attack-damage-ability-modifier-choice.ts";

export {
  endBattleRuntimeTurn,
  openCreatureFallsRuntimeInterruptWindow,
  resolveBattleRuntimeInterrupt,
  resolveBattleRuntimeSubject,
  resolveBattleSubject,
  type BattleRuntimeResolutionInput,
  type BattleRuntimeResolutionResult,
} from "./battle-session-execution.ts";

export {
  resolveBattlePossessionAttempt,
  type BattlePossessionAttemptInput,
} from "./battle-reducer/spell-condition-effects-helpers.ts";

export {
  resolveFailedSavingThrowReroll,
  type FailedSavingThrowRerollInput,
  type FailedSavingThrowRerollIssue,
  type FailedSavingThrowRerollIssueReason,
  type FailedSavingThrowRerollResult,
} from "./battle-reducer/failed-saving-throw-reroll.ts";

export {
  deriveCreatureSpaceTraversalMovementFactFromTableRoute,
  type BattleCreatureSpaceOccupantFootprintFact,
  type BattleCreatureSpaceSizeRelationToMover,
  type BattleCreatureSpaceTableRoute,
  type BattleCreatureSpaceTableRouteDerivationInput,
  type BattleCreatureSpaceTableRouteDerivationInvalidReason,
  type BattleCreatureSpaceTableRouteDerivationResult,
  type BattleRouteDerivedCreatureSpaceTraversalMovementFact,
} from "./battle-reducer/creature-space-table-route.ts";

export {
  ATTACK_DAMAGE_RIDER_SUPPORT_PROFILE,
  ATTACK_DAMAGE_REDUCTION_ZERO_DAMAGE_REDIRECT_SUPPORT_PROFILE,
  ATTACK_ACTION_AREA_SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  ATTACK_ACTION_ATTACK_COUNT_SCALING_SUPPORT_PROFILE,
  BATTLE_UNIT_SUPPORT_PROFILES,
  ATTACK_ROLL_MISS_TO_HIT_REPLACEMENT_SUPPORT_PROFILE,
  BARDIC_INSPIRATION_GRANT_SUPPORT_PROFILE,
  DRUID_WILD_COMPANION_SPELL_CAST_SUPPORT_PROFILE,
  DRUID_WILD_SHAPE_KNOWN_FORM_SUPPORT_PROFILE,
  FAILED_ABILITY_CHECK_RESOURCE_BOOST_SUPPORT_PROFILE,
  FAILED_SAVING_THROW_REROLL_SUPPORT_PROFILE,
  PASSIVE_ABILITY_CHECK_ROLL_MODE_SUPPORT_PROFILE,
  PASSIVE_ARMOR_CLASS_BONUS_SUPPORT_PROFILE,
  PASSIVE_RANGED_ATTACK_ROLL_BONUS_SUPPORT_PROFILE,
  PASSIVE_SAVING_THROW_ROLL_MODE_SUPPORT_PROFILE,
  PASSIVE_SPEED_BONUS_SUPPORT_PROFILE,
  ACROBATIC_MOVEMENT_SUPPORT_PROFILE,
  CREATURE_SPACE_MOVEMENT_PERMISSION_SUPPORT_PROFILE,
  HIDE_ACTION_OBSCUREMENT_PERMISSION_SUPPORT_PROFILE,
  REACTION_ROLL_OR_DAMAGE_REDUCTION_SUPPORT_PROFILE,
  SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  WEAPON_DAMAGE_DICE_ROLL_CHOICE_SUPPORT_PROFILE,
  WEAPON_MASTERY_CLEAVE_SUPPORT_PROFILE,
  WEAPON_MASTERY_SAP_SUPPORT_PROFILE,
  WEAPON_MASTERY_TOPPLE_SUPPORT_PROFILE,
  WEAPON_OR_UNARMED_CRITICAL_RANGE_19_SUPPORT_PROFILE,
  LIGHT_EXTRA_ATTACK_DAMAGE_ABILITY_MODIFIER_SUPPORT_PROFILE,
  MARTIAL_ARTS_ATTACK_PROJECTION_SUPPORT_PROFILE,
  MONK_FOCUS_BATTLE_OPTIONS_SUPPORT_PROFILE,
  ZERO_HIT_POINT_REPLACEMENT_SUPPORT_PROFILE,
  battleAttackDamageRiderSupportForUnit,
  battleAttackActionAttackCountScalingSupportForUnit,
  battleBonusActionStandardActionSupportForUnit,
  battleBardicInspirationGrantSupportForUnit,
  battleDruidWildCompanionSpellCastSupportForUnit,
  battleDruidWildShapeKnownFormSupportForUnit,
  battleAttackRollMissToHitReplacementSupportForUnit,
  battleFailedAbilityCheckResourceBoostSupportForUnit,
  battleFailedSavingThrowRerollSupportForUnit,
  battlePassiveAbilityCheckRollModeSupportForUnit,
  battlePassiveArmorClassBonusSupportForUnit,
  battlePassiveDamageResistanceSupportForUnit,
  battlePassiveRangedAttackRollBonusSupportForUnit,
  battlePassiveSavingThrowRollModeSupportForUnit,
  battlePassiveSpeedBonusSupportForUnit,
  battleAcrobaticMovementSupportForUnit,
  battleCreatureSpaceMovementPermissionSupportForUnit,
  battleHideActionObscurementPermissionSupportForUnit,
  battleReactionRollOrDamageReductionSupportForUnit,
  battleSaveDamageReplacementSupportForUnit,
  parseSupportedUnitFeatureProfile,
  battleUnitRefWithSupportProfiles,
  battleUnitSupportProfilesForUnit,
  battleAttackDamageDieFloorSupportForUnit,
  failedSavingThrowRerollProfileForUnit,
  battleLightExtraAttackDamageAbilityModifierSupportForUnit,
  battleWeaponDamageDiceRollChoiceSupportForUnit,
  battleWeaponMasteryCleaveSupportForUnit,
  battleWeaponMasteryPushSupportForUnit,
  battleWeaponMasterySapSupportForUnit,
  battleWeaponMasterySlowSupportForUnit,
  battleWeaponMasteryToppleSupportForUnit,
  battleTacticalMasterReplacementSupportForUnit,
  battleMartialArtsAttackProjectionSupportForUnit,
  battleMonkFocusBattleOptionsSupportForUnit,
  battleStunningStrikeSupportForUnit,
  battleInitiativeProficiencyAndSwapSupportForUnit,
  battleWeaponOrUnarmedCriticalRange19SupportForUnit,
  battleZeroHitPointReplacementSupportForUnit,
  attackActionAttackCountScalingProfileForUnit,
  ATTACK_DAMAGE_DIE_FLOOR_SUPPORT_PROFILE,
  INITIATIVE_PROFICIENCY_AND_SWAP_SUPPORT_PROFILE,
  STUNNING_STRIKE_SUPPORT_PROFILE,
  TACTICAL_MASTER_REPLACEMENT_MASTERY_PROPERTIES,
  TACTICAL_MASTER_REPLACEMENT_SUPPORT_PROFILE,
  WEAPON_MASTERY_PUSH_SUPPORT_PROFILE,
  WEAPON_MASTERY_SLOW_SUPPORT_PROFILE,
  initiativeProficiencyAndSwapProfileForUnit,
  PASSIVE_DAMAGE_RESISTANCE_SUPPORT_PROFILE,
  passiveArmorClassBonusProfileForUnit,
  passiveAbilityCheckRollModeProfileForUnit,
  creatureSpaceMovementPermissionProfileForUnit,
  hideActionObscurementPermissionProfileForUnit,
  passiveDamageResistanceProfileForUnit,
  attackDamageDieFloorProfileForUnit,
  lightExtraAttackDamageAbilityModifierProfileForUnit,
  martialArtsAttackProjectionProfileForUnit,
  passiveRangedAttackRollBonusProfileForUnit,
  passiveSavingThrowRollModeProfileForUnit,
  passiveSpeedBonusProfileForUnit,
  acrobaticMovementProfileForUnit,
  type AcrobaticMovementProfile,
  type BattleAttackDamageRiderSupport,
  type BattleAttackDamageDieFloorSupport,
  type BattleLightExtraAttackDamageAbilityModifierSupport,
  type BattleLightExtraAttackDamageAbilityModifierSupportProfile,
  type BattleAttackActionAttackCountScalingSupport,
  type BattleAttackActionAttackCountScalingSupportProfile,
  type BattleAttackActionAreaSaveDamageReplacementSupport,
  type BattleHideActionObscurementPermissionSupportProfile,
  type BattleAttackActionAreaSaveDamageReplacementSupportProfile,
  type BattleAttackRollMissToHitReplacementSupport,
  type BattleAttackRollMissToHitReplacementSupportProfile,
  type BattleBonusActionStandardActionSupport,
  type BattleDruidWildShapeKnownFormSupport,
  type BattleDruidWildShapeKnownFormSupportProfile,
  type SupportedDruidWildShapeKnownFormProfile,
  type BattleFailedAbilityCheckResourceBoostSupport,
  type BattleFailedAbilityCheckResourceBoostSupportProfile,
  type BattleInitiativeProficiencyAndSwapSupport,
  type BattleInitiativeProficiencyAndSwapSupportProfile,
  type BattlePassiveArmorClassBonusSupport,
  type BattlePassiveAbilityCheckRollModeSupport,
  type BattlePassiveAbilityCheckRollModeSupportProfile,
  type BattlePassiveDamageResistanceSupport,
  type BattlePassiveDamageResistanceSupportProfile,
  type BattlePassiveRangedAttackRollBonusSupport,
  type BattlePassiveRangedAttackRollBonusSupportProfile,
  type BattlePassiveSavingThrowRollModeSupport,
  type BattlePassiveSavingThrowRollModeSupportProfile,
  type BattlePassiveSpeedBonusSupport,
  type BattleAcrobaticMovementSupport,
  type BattleAcrobaticMovementSupportProfile,
  type BattleCreatureSpaceMovementPermissionSupport,
  type BattleCreatureSpaceMovementPermissionSupportProfile,
  type CreatureSpaceMovementPermissionProfile,
  type BattleMonkFocusBattleOptionsSupport,
  type BattleMonkFocusBattleOptionsSupportProfile,
  type BattleStunningStrikeSupport,
  type BattleStunningStrikeSupportProfile,
  type BattleReactionRollOrDamageReductionSupport,
  type BattleSaveDamageReplacementSupport,
  type BattleUnitSupportProfile,
  type BattleUnitSupportProfileIssue,
  type BattleUnitSupportProfileSourceFacts,
  type BattleWeaponOrUnarmedCriticalRange19Support,
  type BattleWeaponDamageDiceRollChoiceSupport,
  type BattleWeaponMasteryCleaveSupport,
  type BattleWeaponMasterySapSupport,
  type BattleWeaponMasteryToppleSupport,
  type BattleMartialArtsAttackProjectionSupport,
  type BattleZeroHitPointReplacementSupport,
  type FailedAbilityCheckResourceBoostProfile,
  type InitiativeProficiencyAndSwapProfile,
  type PassiveArmorClassBonusProfile,
  type PassiveAbilityCheckRollModeProfile,
  type PassiveDamageResistanceProfile,
  type AttackRollMissToHitReplacementProfile,
  type AttackDamageDieFloorProfile,
  type LightExtraAttackDamageAbilityModifierProfile,
  type PassiveRangedAttackRollBonusProfile,
  type PassiveSavingThrowRollModeProfile,
  type PassiveSpeedBonusProfile,
  type MartialArtsAttackProjectionProfile,
  type StunningStrikeProfile,
  type WeaponDamageDiceRollChoiceProfile,
} from "./unit-feature-support.ts";

export {
  activeDruidWildShapeEffect,
  activeDruidWildShapeForm,
  combatantAbilityCheckModifier,
  combatantD20AbilityModifier,
  combatantD20AbilityScore,
  combatantD20ProficiencyBonus,
  combatantDruidWildShapeArmorClassState,
  combatantEffectiveSize,
  combatantHasActiveDruidWildShape,
  combatantSavingThrowModifier,
  combatantSkillModifier,
  revertDruidWildShapeForm,
  removeEndedDruidWildShapeEffects,
} from "./battle-reducer/druid-wild-shape.ts";

export {
  battleShapeShiftedRuntimeState,
  combatantIsShapeShifted,
  combatantShapeShiftingSuppressed,
  spellShapeShiftedRuntimeState,
  shapeShiftedRuntimeState,
  revertShapeShiftedCombatantToTrueForm,
  revertShapeShiftedRuntimeState,
  trueFormRuntimeState,
  type BattleShapeShiftReplacementFormFacts,
  type BattleShapeShiftReversionOwner,
  type BattleShapeShiftReversionResult,
  type BattleShapeShiftSource,
  type BattleShapeShiftRuntimeOwner,
  type BattleShapeShiftedRuntimeState,
  type BattleShapeShiftTrueFormFacts,
  type SpellShapeShiftedFormActiveEffect,
} from "./battle-reducer/shape-shifting.ts";

export {
  admitCharacterWeaponAttackExecutionWeapon,
  admitCharacterWeaponExecutionWeapon,
} from "./character-weapon-execution-admission.ts";
