import { Match } from "effect";
import type { SupportedSpellInvocation } from "./battle-state-execution.ts";
import type { SpellProcedureExecution } from "./procedure-execution/spell-procedure-execution.ts";
import { spellRuleExecutionFactsWithCastingSource } from "./procedure-execution/spell-rule-facts.ts";
import {
  isCantripSpellAccess,
  isLeveledSpellAccess,
} from "./procedure-execution/spell-invocation-vocabulary.ts";
export function spellProcedureExecution<
  Invocation extends SupportedSpellInvocation,
>(invocation: Invocation): SpellProcedureExecution<Invocation>;
export function spellProcedureExecution(
  invocation: SupportedSpellInvocation,
): SpellProcedureExecution {
  const spellRuleFacts = spellRuleExecutionFactsWithCastingSource(
    invocation.spell.spellDefinitionRuleFacts,
    invocation.spell.castingSource,
  );
  return Match.value(invocation).pipe(
    Match.discriminatorsExhaustive("procedure")({
      abilityD20TestRollModeSaveGate: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        dc: value.dc,
        failedSaveDamagePenaltyEffect: value.failedSaveDamagePenaltyEffect,
        failedSaveEffect: value.failedSaveEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        successEffect: value.successEffect,
        targeting: value.targeting,
      }),
      afterHitDamage: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        conditionalBonusDamage: value.conditionalBonusDamage,
        damage: value.damage,
        procedure: value.procedure,
        resource: value.resource,
      }),
      afterHitDamageAndIllumination: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        damage: value.damage,
        illumination: value.illumination,
        procedure: value.procedure,
        resource: value.resource,
      }),
      afterHitSaveGatedCondition: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        dc: value.dc,
        effect: value.effect,
        procedure: value.procedure,
        resource: value.resource,
        targeting: value.targeting,
      }),
      afterHitTimedDamageAndSave: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        immediateDamage: value.immediateDamage,
        procedure: value.procedure,
        resource: value.resource,
      }),
      magicSuppressionEmanation: (value) => ({
        spellRuleFacts,
        access: value.access,
        durationTicks: value.durationTicks,
        exceptSources: value.exceptSources,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      attackBurstSaveDamage: (value) => ({
        spellRuleFacts,
        access: value.access,
        attackBonus: value.attackBonus,
        attackKind: value.attackKind,
        burst: value.burst,
        damage: value.damage,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      perceptionGatedAttackRollDefense: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      chainedSpellAttackDamage: (value) => ({
        spellRuleFacts,
        access: value.access,
        attackBonus: value.attackBonus,
        attackKind: value.attackKind,
        damage: value.damage,
        damageTypeChoices: value.damageTypeChoices,
        leapRangeFeet: value.leapRangeFeet,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      chosenDamageResistance: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        damageTypeChoices: value.damageTypeChoices,
        expiresAt: value.expiresAt,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      compelledNextTurnBehavior: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        dc: value.dc,
        procedure: value.procedure,
        resource: value.resource,
        targeting: value.targeting,
        visibility: value.visibility,
      }),
      conditionImmunityAndTurnStartTemporaryHitPoints: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffects: value.activeEffects,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      conditionRemovalProtection: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        procedure: value.procedure,
        protection: value.protection,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      spellCastInterruptionReaction: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        triggerComponents: value.triggerComponents,
        targeting: value.targeting,
      }),
      creatureSizeDecrease: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        dc: value.dc,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      creatureSizeIncrease: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        dc: value.dc,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      creatureTypeProtection: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      damageReduction: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        amount: value.amount,
        damageTypeChoices: value.damageTypeChoices,
        expiresAt: value.expiresAt,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      movableLightManifestation: (value) =>
        Match.value(value).pipe(
          Match.when({ operation: "create" }, (created) => ({
            spellRuleFacts,
            access: created.access,
            actionCost: created.actionCost,
            dimRadiusFeet: created.dimRadiusFeet,
            expiresAt: created.expiresAt,
            form: created.form,
            maxMoveFeet: created.maxMoveFeet,
            operation: created.operation,
            procedure: created.procedure,
            rangeFeet: created.rangeFeet,
            resource: created.resource,
            spacingFeet: created.spacingFeet,
          })),
          Match.when({ operation: "reposition" }, (reposition) => ({
            spellRuleFacts,
            access: reposition.access,
            actionCost: reposition.actionCost,
            activeEffectRef: reposition.activeEffectRef,
            maxMoveFeet: reposition.maxMoveFeet,
            operation: reposition.operation,
            procedure: reposition.procedure,
            rangeFeet: reposition.rangeFeet,
            resource: reposition.resource,
            sourceManifestationProcedureRef:
              reposition.sourceManifestationProcedureRef,
            spacingFeet: reposition.spacingFeet,
          })),
          Match.exhaustive,
        ),
      directCondition: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      directConditionRemoval: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        conditionChoices: value.conditionChoices,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      directHitPointRestoration: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        healing: value.healing,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      grantedAreaSaveDamageAction: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        ability: value.ability,
        activeEffect: value.activeEffect,
        coneLengthFeet: value.coneLengthFeet,
        dc: value.dc,
        damageDice: value.damageDice,
        damageDieSize: value.damageDieSize,
        damageTypeChoices: value.damageTypeChoices,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      grantedAlternateActionCost: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      fallingCreatureMitigationReaction: (value) => ({
        spellRuleFacts,
        access: value.access,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      persistentAreaSaveDamage: (value) =>
        Match.value(value).pipe(
          Match.when({ lifecycle: { kind: "stationary" } }, (stationary) => ({
            spellRuleFacts,
            ability: stationary.ability,
            access: stationary.access,
            damage: stationary.damage,
            dc: stationary.dc,
            durationTicks: stationary.durationTicks,
            lifecycle: stationary.lifecycle,
            procedure: stationary.procedure,
            rangeFeet: stationary.rangeFeet,
            resource: stationary.resource,
            targeting: stationary.targeting,
          })),
          Match.when(
            { lifecycle: { kind: "sourceTurnTranslation" } },
            (translation) => ({
              spellRuleFacts,
              ability: translation.ability,
              access: translation.access,
              damage: translation.damage,
              dc: translation.dc,
              durationTicks: translation.durationTicks,
              lifecycle: translation.lifecycle,
              procedure: translation.procedure,
              rangeFeet: translation.rangeFeet,
              resource: translation.resource,
              targeting: translation.targeting,
            }),
          ),
          Match.when(
            {
              lifecycle: {
                kind: "casterActionReposition",
                collisionDisposition: "stopAndAffectAdjacent",
              },
            },
            (collision) => ({
              spellRuleFacts,
              ability: collision.ability,
              access: collision.access,
              damage: collision.damage,
              dc: collision.dc,
              durationTicks: collision.durationTicks,
              lifecycle: collision.lifecycle,
              procedure: collision.procedure,
              ramMaxMoveFeet: collision.ramMaxMoveFeet,
              rangeFeet: collision.rangeFeet,
              resource: collision.resource,
              targeting: collision.targeting,
            }),
          ),
          Match.when(
            {
              lifecycle: {
                kind: "casterActionReposition",
                collisionDisposition: "ignoreObstacles",
              },
            },
            (directed) => ({
              spellRuleFacts,
              ability: directed.ability,
              access: directed.access,
              damage: directed.damage,
              dc: directed.dc,
              durationTicks: directed.durationTicks,
              lifecycle: directed.lifecycle,
              procedure: directed.procedure,
              rangeFeet: directed.rangeFeet,
              repositionMaxMoveFeet: directed.repositionMaxMoveFeet,
              resource: directed.resource,
              targeting: directed.targeting,
            }),
          ),
          Match.exhaustive,
        ),
      persistentAreaTrait: (value) => ({
        spellRuleFacts,
        access: value.access,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      persistentAreaSaveCondition: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      directionalPersistentArea: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        durationTicks: value.durationTicks,
        movementCost: value.movementCost,
        procedure: value.procedure,
        pushDistanceFeet: value.pushDistanceFeet,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      compositeTargetBuffWithAftermath: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffects: value.activeEffects,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      heldLight: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        expiresAt: value.expiresAt,
        hurl: value.hurl,
        light: value.light,
        procedure: value.procedure,
        resource: value.resource,
      }),
      /* v8 ignore start -- @preserve -- Held-light hurl is synthesized from an admitted active effect; it is never an authored character spell invocation at this projection boundary. */
      heldLightHurl: (value) => ({
        spellRuleFacts,
        access: value.access,
        attackBonus: value.attackBonus,
        attackKind: value.attackKind,
        damage: value.damage,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        sourceEffectRef: value.sourceEffectRef,
        sourceHeldLightProcedureRef: value.sourceHeldLightProcedureRef,
        targeting: value.targeting,
      }),
      saveGatedConditionWithRepeat: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        dc: value.dc,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      /* v8 ignore stop -- @preserve */
      saveGatedAreaControl: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        dc: value.dc,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      fixedCostMovementReplacement: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      controlledVerticalSuspension: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        dc: value.dc,
        maxAltitudeChangeFeet: value.maxAltitudeChangeFeet,
        maxInitialRiseFeet: value.maxInitialRiseFeet,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      magicalDarknessPointOrigin: (value) => ({
        spellRuleFacts,
        access: value.access,
        dispelledSpellCreatedLightMaxSpellLevel:
          value.dispelledSpellCreatedLightMaxSpellLevel,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      weaponAttackDamageEnhancement: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        bonus: value.bonus,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        resource: value.resource,
      }),
      makeStable: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
      }),
      markedDamageRider: (value) =>
        Match.value(value).pipe(
          Match.when({ action: "cast" }, (cast) => {
            return {
              spellRuleFacts,
              abilityCheckBehavior: cast.abilityCheckBehavior,
              access: cast.access,
              action: cast.action,
              actionCost: cast.actionCost,
              damage: cast.damage,
              expiresAt: cast.expiresAt,
              procedure: cast.procedure,
              rangeFeet: cast.rangeFeet,
              resource: cast.resource,
              retargetTiming: cast.retargetTiming,
              targeting: cast.targeting,
            };
          }),
          Match.when({ action: "transfer" }, (transfer) => ({
            action: transfer.action,
            activeEffectRef: transfer.activeEffect.effectRef,
            activeEffectSourceProcedureRef:
              transfer.activeEffect.sourceProcedureRef,
            procedure: transfer.procedure,
          })),
          Match.exhaustive,
        ),
      duplicateHitInterception: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      objectContactDamage: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        damage: value.damage,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      objectContactDamageRepeat: (value) => ({
        activeEffectRef: value.activeEffect.effectRef,
        activeEffectSourceProcedureRef: value.activeEffect.sourceProcedureRef,
        procedure: value.procedure,
      }),
      objectLight: (value) =>
        Match.value(value).pipe(
          Match.when({ access: isCantripSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            actionCost: value.actionCost,
            expiresAt: value.expiresAt,
            light: value.light,
            procedure: value.procedure,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.when({ access: isLeveledSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            actionCost: value.actionCost,
            expiresAt: value.expiresAt,
            light: value.light,
            procedure: value.procedure,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.exhaustive,
        ),
      ongoingSpellEnd: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        abilityCheckDcBase: value.abilityCheckDcBase,
        resource: value.resource,
      }),
      persistentArmorEffect: (value) =>
        Match.value(value).pipe(
          Match.when({ access: isLeveledSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            activeEffect: value.activeEffect,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
          })),
          Match.when({ access: { tag: "armorOfShadows" } }, (value) => ({
            spellRuleFacts,
            access: value.access,
            activeEffect: value.activeEffect,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
          })),
          Match.exhaustive,
        ),
      repeatedDamageAllocation: (value) => ({
        spellRuleFacts,
        access: value.access,
        damage: value.damage,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      rollModifier: (value) =>
        "abilityChoiceApplication" in value
          ? {
              spellRuleFacts,
              abilityChoiceApplication: value.abilityChoiceApplication,
              abilityChoices: value.abilityChoices,
              access: value.access,
              actionCost: value.actionCost,
              effect: value.effect,
              procedure: value.procedure,
              rangeFeet: value.rangeFeet,
              resource: value.resource,
              saveGate: value.saveGate,
              targeting: value.targeting,
            }
          : {
              spellRuleFacts,
              abilityChoices: value.abilityChoices,
              access: value.access,
              actionCost: value.actionCost,
              effect: value.effect,
              procedure: value.procedure,
              rangeFeet: value.rangeFeet,
              resource: value.resource,
              saveGate: value.saveGate,
              targeting: value.targeting,
            },
      targetingSaveInterdiction: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      saveGatedAttackRollAdvantage: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        effect: value.effect,
        illumination: value.illumination,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      saveGatedCondition: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        effect: value.effect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        saveRollModeRule: value.saveRollModeRule,
        targetCreatureTypes: value.targetCreatureTypes,
        targeting: value.targeting,
      }),
      saveGatedConditionImmunity: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        activeEffects: value.activeEffects,
        dc: value.dc,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targetCreatureTypes: value.targetCreatureTypes,
        targeting: value.targeting,
      }),
      saveGatedDamage: (value) =>
        Match.value(value).pipe(
          Match.when({ access: isCantripSpellAccess }, (value) => ({
            spellRuleFacts,
            ability: value.ability,
            access: value.access,
            additionalDamageComponents: value.additionalDamageComponents,
            castingTime: value.castingTime,
            damage: value.damage,
            dc: value.dc,
            failedSaveAbilityChoices: value.failedSaveAbilityChoices,
            failedSaveConditionEffects: value.failedSaveConditionEffects,
            failedSavePostDamageRiders: value.failedSavePostDamageRiders,
            postSaveAreaEffect: value.postSaveAreaEffect,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            saveRollModeRule: value.saveRollModeRule,
            successDamage: value.successDamage,
            targeting: value.targeting,
          })),
          Match.when({ access: isLeveledSpellAccess }, (value) => ({
            spellRuleFacts,
            ability: value.ability,
            access: value.access,
            additionalDamageComponents: value.additionalDamageComponents,
            castingTime: value.castingTime,
            damage: value.damage,
            dc: value.dc,
            failedSaveAbilityChoices: value.failedSaveAbilityChoices,
            failedSaveConditionEffects: value.failedSaveConditionEffects,
            failedSavePostDamageRiders: value.failedSavePostDamageRiders,
            postSaveAreaEffect: value.postSaveAreaEffect,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            saveRollModeRule: value.saveRollModeRule,
            successDamage: value.successDamage,
            targeting: value.targeting,
          })),
          Match.exhaustive,
        ),
      scalarBuff: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        effect: value.effect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      seeInvisibleObserverSight: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      selfTeleport: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        maxDistanceFeet: value.maxDistanceFeet,
        procedure: value.procedure,
        resource: value.resource,
      }),
      selfTransformationMode: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        expiresAt: value.expiresAt,
        modeChoices: value.modeChoices,
        naturalWeaponFacts: value.naturalWeaponFacts,
        procedure: value.procedure,
        resource: value.resource,
      }),
      triggeredArmorDefense: (value) => ({
        spellRuleFacts,
        access: value.access,
        armorClassBonus: value.armorClassBonus,
        negatesRepeatedDamageAllocation: value.negatesRepeatedDamageAllocation,
        procedure: value.procedure,
        resource: value.resource,
      }),
      saveGatedTurnConstraintBundle: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        actionCost: value.actionCost,
        constraints: value.constraints,
        dc: value.dc,
        durationTicks: value.durationTicks,
        maxTargets: value.maxTargets,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      persistentAreaSaveComposite: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      stagedSaveCondition: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        automaticSuccessPredicates: value.automaticSuccessPredicates,
        dc: value.dc,
        durationTicks: value.durationTicks,
        escapeAction: value.escapeAction,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      spellAttackDamage: (value) =>
        Match.value(value).pipe(
          Match.when({ access: isCantripSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            attackBonus: value.attackBonus,
            attackKind: value.attackKind,
            damage: value.damage,
            laterDamage: value.laterDamage,
            missDamage: value.missDamage,
            objectHitEffect: value.objectHitEffect,
            postDamageRiders: value.postDamageRiders,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.when({ access: isLeveledSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            attackBonus: value.attackBonus,
            attackKind: value.attackKind,
            damage: value.damage,
            laterDamage: value.laterDamage,
            missDamage: value.missDamage,
            objectHitEffect: value.objectHitEffect,
            postDamageRiders: value.postDamageRiders,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.exhaustive,
        ),
      spellAttackSequence: (value) =>
        Match.value(value).pipe(
          Match.when({ access: isCantripSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            attackBonus: value.attackBonus,
            attackKind: value.attackKind,
            damage: value.damage,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.when({ access: isLeveledSpellAccess }, (value) => ({
            spellRuleFacts,
            access: value.access,
            attackBonus: value.attackBonus,
            attackKind: value.attackKind,
            damage: value.damage,
            procedure: value.procedure,
            rangeFeet: value.rangeFeet,
            resource: value.resource,
            targeting: value.targeting,
          })),
          Match.exhaustive,
        ),
      spellCreatedHeldObject: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      /* v8 ignore start -- @preserve -- The held-object attack is synthesized from an admitted active effect; it is never an authored character spell invocation at this projection boundary. */
      spellCreatedHeldObjectAttack: (value) => ({
        spellRuleFacts,
        access: value.access,
        sourceEffectRef: value.sourceEffectRef,
        sourceHeldObjectProcedureRef: value.sourceHeldObjectProcedureRef,
        attackBonus: value.attackBonus,
        attackKind: value.attackKind,
        damage: value.damage,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      /* v8 ignore stop -- @preserve */
      /* v8 ignore start -- @preserve -- Held-object re-evocation is synthesized from an admitted active effect; it is never an authored character spell invocation at this projection boundary. */
      spellCreatedHeldObjectReEvoke: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        sourceEffectRef: value.sourceEffectRef,
        sourceHeldObjectProcedureRef: value.sourceHeldObjectProcedureRef,
        procedure: value.procedure,
        resource: value.resource,
      }),
      /* v8 ignore stop -- @preserve */
      spellHostedWeaponAttack: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        attackBonus: value.attackBonus,
        bonusDamage: value.bonusDamage,
        componentWeaponObjectId: value.componentWeapon.objectId,
        damageTypeChoices: value.damageTypeChoices,
        procedure: value.procedure,
        resource: value.resource,
        spellcastingAbilityModifier: value.spellcastingAbilityModifier,
      }),
      areaMovementDistanceDamage: (value) => ({
        spellRuleFacts,
        access: value.access,
        damage: value.damage,
        damagePerFeet: value.damagePerFeet,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
      spatialMeleeSpellAttackProxy: (value) =>
        Match.value(value).pipe(
          Match.when({ operation: "createAndAttack" }, (created) => {
            return {
              spellRuleFacts,
              access: created.access,
              actionCost: created.actionCost,
              attackBonus: created.attackBonus,
              attackKind: created.attackKind,
              damage: created.damage,
              durationTicks: created.durationTicks,
              forceReachFeet: created.forceReachFeet,
              operation: created.operation,
              procedure: created.procedure,
              rangeFeet: created.rangeFeet,
              repeatMoveMaxFeet: created.repeatMoveMaxFeet,
              resource: created.resource,
              targeting: created.targeting,
            };
          }),
          Match.when({ operation: "repositionAndAttack" }, (repeat) => ({
            activeEffectRef: repeat.activeEffect.effectRef,
            activeEffectSourceProcedureRef:
              repeat.activeEffect.sourceProcedureRef,
            operation: repeat.operation,
            procedure: repeat.procedure,
            repeatTargeting: repeat.repeatTargeting,
          })),
          Match.exhaustive,
        ),
      spawnedCompanionLifecycle: (value) => ({
        casting: value.casting,
        control: value.control,
        formEligibility: value.formEligibility,
        initialPlacement: value.initialPlacement,
        lifecycle: value.lifecycle,
        procedure: value.procedure,
        sharedSensesActionCost: value.sharedSensesActionCost,
        telepathyRangeFeet: value.telepathyRangeFeet,
        touchSpellProxy: value.touchSpellProxy,
      }),
      temporaryAbilityCheckRollMode: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        selectedMode: value.selectedMode,
        concurrentDurationModeLimit: value.concurrentDurationModeLimit,
      }),
      linkedDefenseResistanceDamageShare: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        connectionRangeFeet: value.connectionRangeFeet,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
      }),
      weaponAttackOverride: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        attachedWeaponSlot: value.attachedWeaponSlot,
        procedure: value.procedure,
        resource: value.resource,
      }),
      weaponDamageRider: (value) => ({
        spellRuleFacts,
        access: value.access,
        actionCost: value.actionCost,
        activeEffect: value.activeEffect,
        procedure: value.procedure,
        resource: value.resource,
      }),
      persistentAreaSaveConditionEscape: (value) => ({
        spellRuleFacts,
        ability: value.ability,
        access: value.access,
        dc: value.dc,
        durationTicks: value.durationTicks,
        procedure: value.procedure,
        rangeFeet: value.rangeFeet,
        resource: value.resource,
        targeting: value.targeting,
      }),
    }),
  );
}
