import { canSpendAction } from "@dnd/shared-algebras/action-economy-algebra";
import {
  abilityModifier,
  armorClass,
  defaultArmorClassState,
} from "@dnd/shared-algebras/armor-class-algebra";
import {
  applyCondition,
  hasCondition,
} from "@dnd/shared-algebras/conditions-algebra";
import { elapsedTimeTicks } from "@dnd/shared-algebras/elapsed-time-algebra";
import { holeId } from "@dnd/shared-algebras/runtime-hole-algebra";
import {
  attackBonus,
  classLevel,
  damageAmount,
  DieRollResult,
  difficultyClass,
  Hp,
  movementDeltaFeet,
  movementFeet,
  proficiencyBonus,
  resourceCount,
  spellSlotLevel,
  type DamageType,
  type ProficiencyBonus,
} from "@dnd/shared/types";
import { decodeUnitRecordSync } from "@dnd/surface/surface/schema";
import {
  buildStatBlockCatalog,
  srdStatBlockCollection,
} from "@dnd/surface/surface/stat-block-catalog";
import type {
  ActivationPhase,
  ClassName,
  EffectAtom,
  Size,
  SpellRecord,
  StatBlockRecord,
  UnitRecord,
  WeaponProficiency,
} from "@dnd/surface/surface/types";
import {
  buildUnitCatalog,
  srdUnitCollection,
} from "@dnd/surface/surface/unit-catalog";
import * as Either from "effect/Either";
import myceliumStepInput from "../../../plans/unit-profile-coverage/fixtures/classic-non-srd/mycelium_step.json";
import eldritchBlastInput from "../../surface/content/eldritch_blast.json";
import starryWispInput from "../../surface/content/starry_wisp.json";
import trueStrikeInput from "../../surface/content/true_strike.json";
import weaponClubInput from "../../surface/content/weapon_club.json";
import type {
  BattleActiveEffect,
  BattleCreatureState,
  SpellMarkedDamageRider,
  SupportedDamageSpellInvocation,
} from "./battle-reducer.ts";
import { battleCreatureStateWithKnockOutPreservedConditions } from "./battle-reducer/creature-state.ts";
import { applyBattleHitPointDamage } from "./battle-reducer/damage-apply.ts";
import { hideousLaughterRepeatSavingThrowOutcomeHole } from "./battle-reducer/hideous-laughter-repeat-save.ts";
import { conditionApplicationPreventedByCreatureTypeProtection } from "./battle-reducer/spell-condition-effects-helpers.ts";
import {
  applyFailedSaveSpellConditionEffects,
  selectFailedSaveConditionEffect,
} from "./battle-reducer/spells-active-effects.ts";
import {
  applyPreparedSlotSpellDamage,
  spellDamageHole,
  spellSavingThrowOutcomeHole,
  validateSpellDamageFill,
} from "./battle-reducer/spells-damage-fills.ts";
import { supportedPreparedHideousLaughterProfile } from "./battle-reducer/spell-procedure-profiles/hideous-laughter.ts";
import {
  supportedPreparedSaveGateAttackRollAdvantageProfile,
  supportedPreparedSaveGateConditionProfile,
} from "./battle-reducer/spell-procedure-profiles/_save-gate-helpers.ts";
import { supportedPreparedSleepTargetAdmissionProfile } from "./battle-reducer/spell-procedure-profiles/sleep-target-admission.ts";
import { supportedPreparedHellishRebukeReactionSpellProfile } from "./battle-reducer/spells-profiles.ts";
import { validateSavingThrowOutcomes } from "./battle-reducer/spells-resolve-save-gates.ts";
import { characterBattleResourceForUnit } from "./character-battle-resources.ts";
import {
  mechanicsOnlyMyceliumStepUnit,
  myceliumStepUnitId,
} from "./classic-non-srd-mechanics-test-fixtures.ts";
import {
  ATTACK_ACTION_ATTACK_COUNT_SCALING_SUPPORT_PROFILE,
  ATTACK_DAMAGE_DIE_FLOOR_SUPPORT_PROFILE,
  ATTACK_DAMAGE_REDUCTION_ZERO_DAMAGE_REDIRECT_SUPPORT_PROFILE,
  ATTACK_DAMAGE_RIDER_SUPPORT_PROFILE,
  ATTACK_ROLL_MISS_TO_HIT_REPLACEMENT_SUPPORT_PROFILE,
  BARDIC_INSPIRATION_GRANT_SUPPORT_PROFILE,
  applyInitiativeSwap,
  finishInitialInitiativeSetup,
  battleBardicInspirationGrantSupportForUnit,
  battleAreaId,
  battleAttackDamageDieFloorSupportForUnit,
  battleCombatantSide,
  battleCreatureCanBreatheUnderwater,
  battleInitiativeProficiencyAndSwapSupportForUnit,
  battleId,
  battleIlluminationFromLightEmitters,
  battleLightEmitterProjection,
  battleObjectId,
  battleObscurementZones,
  battleCreatureSpaceMovementPermissionSupportForUnit,
  battlePassiveAbilityCheckRollModeSupportForUnit,
  battlePassiveSavingThrowRollModeSupportForUnit,
  battlePerceptionRollModeForObscurement,
  battlePerceptionRollModeForSight,
  battleReactionRollOrDamageReductionSupportForUnit,
  battleSightObscurement,
  battleTablePositionId,
  battleUnitRefWithSupportProfiles,
  battleWeaponItemHasMagicWeaponEnhancement,
  battleWeaponItemMagicWeaponEnhancementBonus,
  breakBattleConcentration,
  cantripSpellInvocationRef,
  characterId,
  combatantId,
  CREATURE_SPACE_MOVEMENT_PERMISSION_SUPPORT_PROFILE,
  creatureSpaceMovementPermissionProfileForUnit,
  discoverBattleActs,
  endTurn,
  FAILED_ABILITY_CHECK_RESOURCE_BOOST_SUPPORT_PROFILE,
  INITIATIVE_PROFICIENCY_AND_SWAP_SUPPORT_PROFILE,
  initiativeScore,
  MARTIAL_ARTS_ATTACK_PROJECTION_SUPPORT_PROFILE,
  objectInvisibleBenefitDenied,
  PASSIVE_ABILITY_CHECK_ROLL_MODE_SUPPORT_PROFILE,
  PASSIVE_ARMOR_CLASS_BONUS_SUPPORT_PROFILE,
  PASSIVE_RANGED_ATTACK_ROLL_BONUS_SUPPORT_PROFILE,
  PASSIVE_SAVING_THROW_ROLL_MODE_SUPPORT_PROFILE,
  passiveAbilityCheckRollModeProfileForUnit,
  REACTION_ROLL_OR_DAMAGE_REDUCTION_SUPPORT_PROFILE,
  resolveBattlePossessionAttempt,
  resolveBattleInterrupt,
  resolveBattleSubject,
  resolveFallDamageLanding,
  resolveFeatherFallLanding,
  resolveFlySpeedGrantEndFallCleanup,
  requiredInitiativeRollModeForCombatant,
  sameBattleSubject,
  SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  snapshotBattle,
  spellId,
  spellSaveDcForCaster,
  spellSlotInvocationRef,
  startBattle,
  startBattleWithInitialInitiativeSetup,
  WEAPON_DAMAGE_DICE_ROLL_CHOICE_SUPPORT_PROFILE,
  WEAPON_OR_UNARMED_CRITICAL_RANGE_19_SUPPORT_PROFILE,
  ZERO_HIT_POINT_REPLACEMENT_SUPPORT_PROFILE,
  type AvailableBattleAct,
  type BattleCreatureInit,
  type BattleFill,
  type BattleFlySpeedGrantEndFallCleanupFrame,
  type BattleHole,
  type BattleObjectDamageDisposition,
  type BattleObjectIgnitionDisposition,
  type BattleSpellAreaChoice,
  type BattleSpellAreaOriginAnchor,
  type BattleSpellSavingThrowOutcomeHole,
  type BattleState,
  type BattleSubject,
  type BattleTargetSpatialFact,
  type CombatantId,
  type EndedFlySpeedGrant,
  type FlyEndCanStopFallReason,
  type FlySpeedGrantEndFallWitness,
  type FlySpeedGrantEndFallWitnessResult,
  type SupportedSpellInvocation,
} from "./index.ts";
import {
  ALTERNATE_ACTION_COST_ACTIONS,
  ATTACK_ACTION_AREA_SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  battleAttackActionAreaSaveDamageReplacementSupportForUnit,
  battleBonusActionDelegatedStandardActionsSupportForUnit,
  battleD20TestNaturalOneRerollSupportForUnit,
  battleEnemyZeroHitPointTemporaryHitPointsSupportForUnit,
  battleFailedAbilityCheckResourceBoostSupportForUnit,
  battleHideActionObscurementPermissionSupportForUnit,
  battleHuntersPreySupportForUnit,
  battleMagicActionAreaSaveDamageHealingSupportForUnit,
  battleMagicActionHealingPoolSupportForUnit,
  battleMartialArtsAttackProjectionSupportForUnit,
  battleMonkFocusBattleOptionsSupportForUnit,
  battleOpenHandTechniqueSupportForUnit,
  battlePaladinSacredWeaponSupportForUnit,
  battlePassiveDamageResistanceSupportForUnit,
  battlePassiveSpeedKindGrantsSupportForUnit,
  battlePotentCantripSupportForUnit,
  battleRemarkableAthleteSupportForUnit,
  battleRogueSteadyAimSupportForUnit,
  battleSpellSlotHealingModifierSupportForUnit,
  BONUS_ACTION_DELEGATED_STANDARD_ACTIONS_SUPPORT_PROFILE,
  BONUS_ACTION_DASH_TEMPORARY_HIT_POINTS_SUPPORT_PROFILE,
  bonusActionDashTemporaryHitPointsProfileForUnit,
  D20_TEST_NATURAL_ONE_REROLL_SUPPORT_PROFILE,
  ENEMY_ZERO_HIT_POINT_TEMPORARY_HIT_POINTS_SUPPORT_PROFILE,
  HIDE_ACTION_OBSCUREMENT_PERMISSION_SUPPORT_PROFILE,
  hideActionObscurementPermissionProfileForUnit,
  HUNTERS_PREY_SUPPORT_PROFILE,
  MAGIC_ACTION_AREA_SAVE_DAMAGE_HEALING_SUPPORT_PROFILE,
  MAGIC_ACTION_HEALING_POOL_SUPPORT_PROFILE,
  MONK_FOCUS_BATTLE_OPTIONS_SUPPORT_PROFILE,
  OPEN_HAND_TECHNIQUE_SUPPORT_PROFILE,
  parseSupportedUnitFeatureProfile,
  PALADIN_SACRED_WEAPON_SUPPORT_PROFILE,
  PASSIVE_DAMAGE_RESISTANCE_SUPPORT_PROFILE,
  passiveDamageResistanceProfileForUnit,
  PASSIVE_SPEED_BONUS_SUPPORT_PROFILE,
  PASSIVE_SPEED_KIND_GRANTS_SUPPORT_PROFILE,
  POTENT_CANTRIP_SUPPORT_PROFILE,
  REMARKABLE_ATHLETE_SUPPORT_PROFILE,
  ROGUE_STEADY_AIM_SUPPORT_PROFILE,
  SPELL_SLOT_HEALING_MODIFIER_SUPPORT_PROFILE,
} from "./unit-feature-support.ts";
export * from "./unit-profile-admission-catalog-support.ts";
export * from "./unit-profile-admission-creature-fixture-support.ts";
export * from "./unit-profile-admission-feature-fixture-support.ts";
export * from "./unit-profile-admission-spell-battle-support.ts";
export * from "./unit-profile-admission-spell-fill-support.ts";
export * from "./unit-profile-admission-spell-record-support.ts";
export {
  abilityModifier,
  ALTERNATE_ACTION_COST_ACTIONS,
  applyBattleHitPointDamage,
  applyCondition,
  applyFailedSaveSpellConditionEffects,
  selectFailedSaveConditionEffect,
  applyPreparedSlotSpellDamage,
  armorClass,
  ATTACK_DAMAGE_DIE_FLOOR_SUPPORT_PROFILE,
  ATTACK_ACTION_ATTACK_COUNT_SCALING_SUPPORT_PROFILE,
  ATTACK_ACTION_AREA_SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  ATTACK_DAMAGE_REDUCTION_ZERO_DAMAGE_REDIRECT_SUPPORT_PROFILE,
  ATTACK_DAMAGE_RIDER_SUPPORT_PROFILE,
  ATTACK_ROLL_MISS_TO_HIT_REPLACEMENT_SUPPORT_PROFILE,
  attackBonus,
  applyInitiativeSwap,
  battleAttackActionAreaSaveDamageReplacementSupportForUnit,
  battleAttackDamageDieFloorSupportForUnit,
  battleD20TestNaturalOneRerollSupportForUnit,
  finishInitialInitiativeSetup,
  BARDIC_INSPIRATION_GRANT_SUPPORT_PROFILE,
  battleAreaId,
  battleBardicInspirationGrantSupportForUnit,
  battleBonusActionDelegatedStandardActionsSupportForUnit,
  battleCombatantSide,
  battleCreatureSpaceMovementPermissionSupportForUnit,
  battleCreatureCanBreatheUnderwater,
  battleCreatureStateWithKnockOutPreservedConditions,
  battleEnemyZeroHitPointTemporaryHitPointsSupportForUnit,
  battleFailedAbilityCheckResourceBoostSupportForUnit,
  battleHideActionObscurementPermissionSupportForUnit,
  battleHuntersPreySupportForUnit,
  battleId,
  battleInitiativeProficiencyAndSwapSupportForUnit,
  battleIlluminationFromLightEmitters,
  battleLightEmitterProjection,
  battleMagicActionAreaSaveDamageHealingSupportForUnit,
  battleMagicActionHealingPoolSupportForUnit,
  battleMartialArtsAttackProjectionSupportForUnit,
  battleMonkFocusBattleOptionsSupportForUnit,
  battleOpenHandTechniqueSupportForUnit,
  battleObjectId,
  battleObscurementZones,
  battlePassiveAbilityCheckRollModeSupportForUnit,
  battlePassiveDamageResistanceSupportForUnit,
  battlePassiveSavingThrowRollModeSupportForUnit,
  battlePassiveSpeedKindGrantsSupportForUnit,
  battlePerceptionRollModeForObscurement,
  battlePerceptionRollModeForSight,
  battlePaladinSacredWeaponSupportForUnit,
  battlePotentCantripSupportForUnit,
  battleReactionRollOrDamageReductionSupportForUnit,
  battleRemarkableAthleteSupportForUnit,
  battleRogueSteadyAimSupportForUnit,
  battleSightObscurement,
  battleSpellSlotHealingModifierSupportForUnit,
  battleTablePositionId,
  battleUnitRefWithSupportProfiles,
  battleWeaponItemHasMagicWeaponEnhancement,
  battleWeaponItemMagicWeaponEnhancementBonus,
  BONUS_ACTION_DELEGATED_STANDARD_ACTIONS_SUPPORT_PROFILE,
  BONUS_ACTION_DASH_TEMPORARY_HIT_POINTS_SUPPORT_PROFILE,
  bonusActionDashTemporaryHitPointsProfileForUnit,
  D20_TEST_NATURAL_ONE_REROLL_SUPPORT_PROFILE,
  breakBattleConcentration,
  buildStatBlockCatalog,
  buildUnitCatalog,
  canSpendAction,
  cantripSpellInvocationRef,
  characterBattleResourceForUnit,
  characterId,
  classLevel,
  combatantId,
  CREATURE_SPACE_MOVEMENT_PERMISSION_SUPPORT_PROFILE,
  creatureSpaceMovementPermissionProfileForUnit,
  conditionApplicationPreventedByCreatureTypeProtection,
  damageAmount,
  decodeUnitRecordSync,
  defaultArmorClassState,
  DieRollResult,
  difficultyClass,
  discoverBattleActs,
  Either,
  elapsedTimeTicks,
  eldritchBlastInput,
  ENEMY_ZERO_HIT_POINT_TEMPORARY_HIT_POINTS_SUPPORT_PROFILE,
  endTurn,
  FAILED_ABILITY_CHECK_RESOURCE_BOOST_SUPPORT_PROFILE,
  hasCondition,
  HIDE_ACTION_OBSCUREMENT_PERMISSION_SUPPORT_PROFILE,
  hideActionObscurementPermissionProfileForUnit,
  hideousLaughterRepeatSavingThrowOutcomeHole,
  holeId,
  Hp,
  HUNTERS_PREY_SUPPORT_PROFILE,
  INITIATIVE_PROFICIENCY_AND_SWAP_SUPPORT_PROFILE,
  initiativeScore,
  MAGIC_ACTION_AREA_SAVE_DAMAGE_HEALING_SUPPORT_PROFILE,
  MAGIC_ACTION_HEALING_POOL_SUPPORT_PROFILE,
  MARTIAL_ARTS_ATTACK_PROJECTION_SUPPORT_PROFILE,
  mechanicsOnlyMyceliumStepUnit,
  MONK_FOCUS_BATTLE_OPTIONS_SUPPORT_PROFILE,
  movementDeltaFeet,
  movementFeet,
  myceliumStepInput,
  myceliumStepUnitId,
  objectInvisibleBenefitDenied,
  OPEN_HAND_TECHNIQUE_SUPPORT_PROFILE,
  parseSupportedUnitFeatureProfile,
  PALADIN_SACRED_WEAPON_SUPPORT_PROFILE,
  PASSIVE_ABILITY_CHECK_ROLL_MODE_SUPPORT_PROFILE,
  PASSIVE_ARMOR_CLASS_BONUS_SUPPORT_PROFILE,
  PASSIVE_DAMAGE_RESISTANCE_SUPPORT_PROFILE,
  passiveAbilityCheckRollModeProfileForUnit,
  passiveDamageResistanceProfileForUnit,
  PASSIVE_RANGED_ATTACK_ROLL_BONUS_SUPPORT_PROFILE,
  PASSIVE_SAVING_THROW_ROLL_MODE_SUPPORT_PROFILE,
  PASSIVE_SPEED_BONUS_SUPPORT_PROFILE,
  PASSIVE_SPEED_KIND_GRANTS_SUPPORT_PROFILE,
  POTENT_CANTRIP_SUPPORT_PROFILE,
  proficiencyBonus,
  REACTION_ROLL_OR_DAMAGE_REDUCTION_SUPPORT_PROFILE,
  REMARKABLE_ATHLETE_SUPPORT_PROFILE,
  resolveBattlePossessionAttempt,
  resolveBattleInterrupt,
  resolveBattleSubject,
  resolveFallDamageLanding,
  resolveFeatherFallLanding,
  resolveFlySpeedGrantEndFallCleanup,
  requiredInitiativeRollModeForCombatant,
  resourceCount,
  ROGUE_STEADY_AIM_SUPPORT_PROFILE,
  sameBattleSubject,
  SAVE_DAMAGE_REPLACEMENT_SUPPORT_PROFILE,
  snapshotBattle,
  spellDamageHole,
  spellId,
  spellSaveDcForCaster,
  spellSavingThrowOutcomeHole,
  spellSlotInvocationRef,
  spellSlotLevel,
  SPELL_SLOT_HEALING_MODIFIER_SUPPORT_PROFILE,
  srdStatBlockCollection,
  srdUnitCollection,
  starryWispInput,
  startBattle,
  startBattleWithInitialInitiativeSetup,
  supportedPreparedHellishRebukeReactionSpellProfile,
  supportedPreparedHideousLaughterProfile,
  supportedPreparedSaveGateAttackRollAdvantageProfile,
  supportedPreparedSaveGateConditionProfile,
  supportedPreparedSleepTargetAdmissionProfile,
  trueStrikeInput,
  validateSavingThrowOutcomes,
  validateSpellDamageFill,
  WEAPON_DAMAGE_DICE_ROLL_CHOICE_SUPPORT_PROFILE,
  WEAPON_OR_UNARMED_CRITICAL_RANGE_19_SUPPORT_PROFILE,
  weaponClubInput,
  ZERO_HIT_POINT_REPLACEMENT_SUPPORT_PROFILE,
};
export type {
  ActivationPhase,
  AvailableBattleAct,
  BattleActiveEffect,
  BattleCreatureInit,
  BattleCreatureState,
  BattleFill,
  BattleFlySpeedGrantEndFallCleanupFrame,
  BattleHole,
  BattleObjectDamageDisposition,
  BattleObjectIgnitionDisposition,
  BattleSpellAreaChoice,
  BattleSpellAreaOriginAnchor,
  BattleSpellSavingThrowOutcomeHole,
  BattleState,
  BattleSubject,
  BattleTargetSpatialFact,
  ClassName,
  CombatantId,
  DamageType,
  EndedFlySpeedGrant,
  EffectAtom,
  FlyEndCanStopFallReason,
  FlySpeedGrantEndFallWitness,
  FlySpeedGrantEndFallWitnessResult,
  ProficiencyBonus,
  Size,
  SpellMarkedDamageRider,
  SpellRecord,
  StatBlockRecord,
  SupportedDamageSpellInvocation,
  SupportedSpellInvocation,
  UnitRecord,
  WeaponProficiency,
};
