import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import { describe, expect, test } from "vitest";

import {
  ORACLE_PUBLICATION_ARTIFACTS,
  ORACLE_PUBLICATION_MEMBERS,
  serializeOraclePublicationArtifact,
} from "./oracle-publication.ts";
import { checkOraclePublicationSync } from "../scripts/check-schema-sync.ts";

const publicationDirectory = fileURLToPath(
  new URL("../publication/", import.meta.url),
);

type JsonRecord = { readonly [key: string]: unknown };

function isJsonRecord(value: unknown): value is JsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function schemaRecords(root: unknown): readonly JsonRecord[] {
  const records: JsonRecord[] = [];
  const pending: unknown[] = [root];
  const visited = new Set<object>();
  while (pending.length > 0) {
    const value = pending.pop();
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      pending.push(...value);
      continue;
    }
    if (!isJsonRecord(value) || visited.has(value)) continue;
    visited.add(value);
    records.push(value);
    pending.push(...Object.values(value));
  }
  return records;
}

function schemaPropertyNames(root: unknown): readonly string[] {
  const names: string[] = [];
  for (const record of schemaRecords(root)) {
    const properties = record.properties;
    if (!isJsonRecord(properties)) continue;
    names.push(...Object.keys(properties));
  }
  return names;
}

describe("Opaque Oracle schema publication", () => {
  test("committed artifacts are exact generated bytes with independent Ajv roots", () => {
    expect(readdirSync(publicationDirectory).sort()).toEqual(
      [...ORACLE_PUBLICATION_MEMBERS]
        .map((member) => ORACLE_PUBLICATION_ARTIFACTS[member].fileName)
        .sort(),
    );

    for (const member of ORACLE_PUBLICATION_MEMBERS) {
      const artifact = ORACLE_PUBLICATION_ARTIFACTS[member];
      const committedBytes = readFileSync(
        join(publicationDirectory, artifact.fileName),
      );
      expect(committedBytes.equals(artifact.bytes)).toBe(true);
      expect(committedBytes.toString("utf8")).toBe(
        `${JSON.stringify(artifact.schema)}\n`,
      );

      const parsed: unknown = JSON.parse(committedBytes.toString("utf8"));
      expect(isJsonRecord(parsed)).toBe(true);
      if (!isJsonRecord(parsed)) continue;
      expect(parsed.$schema).toBe(
        "https://json-schema.org/draft/2020-12/schema",
      );
      expect(parsed.$id).toBe(artifact.rootId);

      const validate = new Ajv2020({
        strict: false,
        inlineRefs: false,
        code: { optimize: 0 },
      }).compile(parsed);
      expect(validate({})).toBe(false);
    }
  }, 120_000);

  test("sync checking rejects missing, orphaned, malformed, and stale artifacts", () => {
    const temporaryDirectory = mkdtempSync(
      join(tmpdir(), "opaque-oracle-publication-"),
    );
    try {
      for (const member of ORACLE_PUBLICATION_MEMBERS) {
        const artifact = ORACLE_PUBLICATION_ARTIFACTS[member];
        writeFileSync(
          join(temporaryDirectory, artifact.fileName),
          artifact.bytes,
        );
      }
      expect(checkOraclePublicationSync(temporaryDirectory)).toEqual([]);

      writeFileSync(
        join(temporaryDirectory, ORACLE_PUBLICATION_ARTIFACTS.case.fileName),
        "{}\n",
      );
      expect(checkOraclePublicationSync(temporaryDirectory)).toEqual(
        expect.arrayContaining([
          "publication artifact is out of sync: oracle-case.schema.json",
          "publication artifact has the wrong $schema: oracle-case.schema.json",
          "publication artifact has the wrong root $id: oracle-case.schema.json",
        ]),
      );
      writeFileSync(
        join(temporaryDirectory, ORACLE_PUBLICATION_ARTIFACTS.trace.fileName),
        "not json\n",
      );
      expect(checkOraclePublicationSync(temporaryDirectory)).toContainEqual(
        expect.stringContaining(
          "publication artifact is not valid JSON (oracle-trace.schema.json):",
        ),
      );

      rmSync(
        join(
          temporaryDirectory,
          ORACLE_PUBLICATION_ARTIFACTS.evaluationBatch.fileName,
        ),
      );
      writeFileSync(join(temporaryDirectory, "orphan.schema.json"), "{}\n");
      expect(checkOraclePublicationSync(temporaryDirectory)).toEqual(
        expect.arrayContaining([
          "missing publication artifact: oracle-evaluation-batch.schema.json",
          "orphan publication entry: orphan.schema.json",
        ]),
      );
    } finally {
      rmSync(temporaryDirectory, { recursive: true, force: true });
    }
  }, 120_000);

  test("published schema graphs are closed and retain only the selected-build identity exception", () => {
    const forbiddenProperties = new Set([
      "session",
      "frame",
      "globalRole",
      "presentation",
    ]);
    let authoredStartingItemProperties = 0;

    for (const member of ORACLE_PUBLICATION_MEMBERS) {
      const schema = ORACLE_PUBLICATION_ARTIFACTS[member].schema;
      for (const record of schemaRecords(schema)) {
        if (record.type === "object") {
          expect(record.additionalProperties).toBe(false);
        }
        expect(record.type).not.toBe("any");
        expect(record.type).not.toBe("unknown");
        expect(record.declaration).toBeUndefined();
      }

      const propertyNames = schemaPropertyNames(schema);
      for (const propertyName of propertyNames) {
        expect(forbiddenProperties.has(propertyName)).toBe(false);
      }
      if (member === "trace") {
        authoredStartingItemProperties += propertyNames.filter(
          (propertyName) => propertyName === "itemName",
        ).length;
      }
    }

    // Trace embeds a selected CharacterBuildFact. Its authored starting-item
    // label is an identity-bearing selection fact, not a presentation field;
    // AUTHORING.md permits that identity at the selected-build boundary.
    expect(authoredStartingItemProperties).toBeGreaterThan(0);
  });

  test("serialization is compact, deterministic, and newline terminated", () => {
    const sample = { b: [2, 1], a: "stable" };
    expect(serializeOraclePublicationArtifact(sample)).toEqual(
      Buffer.from('{"b":[2,1],"a":"stable"}\n', "utf8"),
    );
    expect(serializeOraclePublicationArtifact(sample)).toEqual(
      serializeOraclePublicationArtifact(sample),
    );
  });
});
